import { resolve } from "node:path";
import { fileWriter } from "./io";
import type { Document } from "./openapi";

export async function generateApiVersion(spec: Document, destDir: string) {
  const outFile = resolve(destDir, "api-version.ts");
  const writer = fileWriter(outFile);
  const version = spec.info?.version || "unknown";

  writer.w(`
// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export const API_VERSION = "${version}";
`);

  await writer.flush();
}
