import { resolve } from "node:path";
import type { OpenAPIV3_1 } from "openapi-types";
import { fileWriter } from "./io";

export async function generateApiVersion(
  spec: OpenAPIV3_1.Document,
  destDir: string,
) {
  const outFile = resolve(destDir, "api-version.ts");
  const writer = fileWriter(outFile);
  const version = spec.info?.version || "unknown";

  writer.w(`
// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export const API_VERSION = "${version}";
`);

  await writer.flush();
}
