import { resolve } from "node:path";
import { Case } from "change-case-all";
import type { OpenAPIV3_1 } from "openapi-types";
import { getSortedSchemas } from "./base";
import { fileWriter } from "./io";
import { schemaNameToTypeName } from "./schema";

/**
 * Generates the main index.ts file with the primary API client class.
 * Creates a client class that instantiates all resource classes as properties.
 */
export async function generateIndex(
  spec: OpenAPIV3_1.Document,
  destDir: string,
) {
  const apiName = "SumUp";

  if (!spec.components) return;

  const outFile = resolve(destDir, "index.ts");
  const writer = fileWriter(outFile);

  writer.w(`
  // Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

  import { HTTPClient } from './client'

  export type { APIConfig } from './client'
  export { APIError, SumUpError } from './core'
  export type { FetchParams } from './core'
  export * from './types'
  `);

  const schemaTypeNames = new Set(
    getSortedSchemas(spec).map((schemaName) =>
      schemaNameToTypeName(schemaName),
    ),
  );

  const tags = spec.tags || [];
  tags.sort((a, b) => (a.name > b.name ? 1 : -1));

  const resourceClassByTag = new Map<string, string>();
  for (const tag of tags) {
    const resourceName = Case.pascal(tag.name);
    const resourceClassName = schemaTypeNames.has(resourceName)
      ? `${resourceName}Resource`
      : resourceName;

    resourceClassByTag.set(tag.name, resourceClassName);

    writer.w(`export * from './resources/${Case.kebab(tag.name)}'`);
    writer.w(
      `import { ${resourceClassName} } from './resources/${Case.kebab(tag.name)}'`,
    );
  }

  writer.w("");
  writer.w(`export class ${apiName} extends HTTPClient {`);
  for (const tag of tags) {
    const resourceClassName = resourceClassByTag.get(tag.name)!;
    writer.w(
      `${Case.camel(tag.name)}: ${resourceClassName} = new ${resourceClassName}(this);`,
    );
  }
  writer.w("}");
  writer.w("");
  writer.w(`export default ${apiName};`);

  await writer.flush();
}
