import { resolve } from "node:path";
import { Case } from "change-case-all";
import type { OpenAPIV3_1 } from "openapi-types";
import { fileWriter } from "./io";
import { schemaNameToTypeName } from "./schema";

type Definition = {
  name: string;
  type: string;
  object: string;
  objectType: string;
};

export function collectEventDefinitions(
  spec: OpenAPIV3_1.Document,
): Definition[] {
  const names = new Set<string>();
  return Object.entries(spec.webhooks ?? {})
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([type, item]) => {
      if ("$ref" in item || !item.post?.operationId)
        throw new Error(`Event ${type}: missing POST operation ID`);
      const operation = item.post as OpenAPIV3_1.OperationObject & {
        "x-object"?: { $ref?: string };
        "x-object-type"?: string;
      };
      const ref = operation["x-object"]?.$ref;
      const objectType = operation["x-object-type"];
      if (!ref?.startsWith("#/components/schemas/") || !objectType)
        throw new Error(
          `Event ${type}: expected local x-object and x-object-type`,
        );
      const schema = ref.slice("#/components/schemas/".length);
      if (!spec.components?.schemas?.[schema])
        throw new Error(`Event ${type}: missing object schema ${schema}`);
      const name = `${Case.pascal(item.post.operationId.replace(/Webhook$/, ""))}Event`;
      if (names.has(name)) throw new Error(`Duplicate event class ${name}`);
      names.add(name);
      return { name, type, object: schemaNameToTypeName(schema), objectType };
    });
}

export async function generateEvents(
  spec: OpenAPIV3_1.Document,
  destDir: string,
): Promise<void> {
  const events = collectEventDefinitions(spec);
  const writer = fileWriter(resolve(destDir, "events.ts"));
  writer.w(`// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.
import type { HTTPClient } from "./client";
import { UnknownEvent, EventBase, type EventPayload } from "./event";`);
  for (const object of [
    ...new Set(events.map((event) => event.object)),
  ].sort()) {
    writer.w(`import type { ${object} } from "./types/${Case.kebab(object)}";`);
  }
  for (const event of events) {
    writer.w(`/** A ${event.type} notification. Call fetchObject() to retrieve the latest ${event.object}. */
export class ${event.name} extends EventBase<${event.object}> {
  declare readonly type: ${JSON.stringify(event.type)};
}`);
  }
  writer.w(`/** Known wire event names and their notification classes. */
export interface EventMap {`);
  for (const event of events)
    writer.w(`${JSON.stringify(event.type)}: ${event.name};`);
  writer.w(`}
/** A recognized event notification or {@link UnknownEvent}. Narrow with instanceof to access a specific resource type. */
export type EventNotification = EventMap[keyof EventMap] | UnknownEvent;
/** @internal Expected object types from the event specification. */
export const eventObjectTypes: Record<string, string> = ${JSON.stringify(Object.fromEntries(events.map((e) => [e.type, e.objectType])))};
/** @internal Construct the typed notification after envelope validation. */
export function createEvent(payload: EventPayload, client: HTTPClient): EventNotification {
  switch (payload.type) {`);
  for (const event of events)
    writer.w(
      `case ${JSON.stringify(event.type)}: return new ${event.name}(payload, client);`,
    );
  writer.w(`default: return new UnknownEvent(payload, client);
  }
}`);
  await writer.flush();
}
