// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Profile information.
 */
export type AccountLegacy = {
  /**
   * Username of the user profile.
   */
  username?: string;
  /**
   * The role of the user.
   */
  type?: "normal" | "operator";
};
