// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Personal address
 */
export type AddressPayloadLegacy = {
  /**
   * Address line 1
   */
  address_line1: string;
  /**
   * Address line 2
   */
  address_line2?: string;
  /**
   * City
   */
  city: string;
  /**
   * Country ISO 3166-1 code
   */
  country: string;
  /**
   * Country region id
   */
  region_id?: number;
  /**
   * Country region name
   */
  region_name?: string;
  /**
   * Postal code
   */
  post_code: string;
  /**
   * Landline number
   */
  landline?: string;
  /**
   * First name
   */
  first_name?: string;
  /**
   * Last name
   */
  last_name?: string;
  /**
   * Company name
   */
  company?: string;
};
