// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CountryDetails } from "./country-details";
import type { TimeoffsetDetails } from "./timeoffset-details";

/**
 * Details of the registered address.
 */
export type AddressWithDetails = {
  /**
   * Address line 1
   */
  address_line1?: string;
  /**
   * Address line 2
   */
  address_line2?: string;
  /**
   * City
   */
  city?: string;
  /**
   * Country ISO 3166-1 code
   */
  country?: string;
  /**
   * Country region id
   */
  region_id?: number;
  /**
   * Region name
   */
  region_name?: string;
  /**
   * Region code
   */
  region_code?: string;
  /**
   * Postal code
   */
  post_code?: string;
  /**
   * Landline number
   */
  landline?: string;
  /**
   * undefined
   */
  first_name?: string;
  /**
   * undefined
   */
  last_name?: string;
  /**
   * undefined
   */
  company?: string;
  country_details?: CountryDetails;
  timeoffset_details?: TimeoffsetDetails;
  /**
   * undefined
   */
  state_id?: string;
};
