// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CountryCode } from "./country-code";

/**
 * An address somewhere in the world. The address fields used depend on the country conventions. For example, in Great Britain, `city` is `post_town`. In the United States, the top-level administrative unit used in addresses is `state`, whereas in Chile it's `region`.
 * Whether an address is valid or not depends on whether the locally required fields are present. Fields not supported in a country will be ignored.
 *
 * Address documentation: https://sumup.roadie.so/docs/default/Component/merchants/merchant/#addresses
 */
export type Address = {
  street_address?: string[];
  /**
   * The postal code (aka. zip code) of the address.
   *
   */
  post_code?: string;
  country: CountryCode;
  /**
   * The city of the address.
   *
   */
  city?: string;
  /**
   * The province where the address is located. This may not be relevant in some countries.
   *
   */
  province?: string;
  /**
   * The region where the address is located. This may not be relevant in some countries.
   *
   */
  region?: string;
  /**
   * A county is a geographic region of a country used for administrative or other purposes in some nations. Used in countries such as Ireland, Romania, etc.
   *
   */
  county?: string;
  /**
   * In Spain, an autonomous community is the first sub-national level of political and administrative division.
   *
   */
  autonomous_community?: string;
  /**
   * A post town is a required part of all postal addresses in the United Kingdom and Ireland, and a basic unit of the postal delivery system.
   *
   */
  post_town?: string;
  /**
   * Most often, a country has a single state, with various administrative divisions. The term "state" is sometimes used to refer to the federated polities that make up the federation. Used in countries such as the United States and Brazil.
   *
   */
  state?: string;
  /**
   * Locality level of the address. Used in countries such as Brazil or Chile.
   *
   */
  neighborhood?: string;
  /**
   * In many countries, terms cognate with "commune" are used, referring to the community living in the area and the common interest. Used in countries such as Chile.
   *
   */
  commune?: string;
  /**
   * A department (French: département, Spanish: departamento) is an administrative or political division in several countries. Used in countries such as Colombia.
   *
   */
  department?: string;
  /**
   * A municipality is usually a single administrative division having corporate status and powers of self-government or jurisdiction as granted by national and regional laws to which it is subordinate. Used in countries such as Colombia.
   *
   */
  municipality?: string;
  /**
   * A district is a type of administrative division that in some countries is managed by the local government. Used in countries such as Portugal.
   *
   */
  district?: string;
  /**
   * A US system of postal codes used by the United States Postal Service (USPS).
   *
   */
  zip_code?: string;
  /**
   * A postal address in Ireland.
   *
   */
  eircode?: string;
};
