// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type Amount = {
  /**
   * Currency ISO 4217 code
   */
  currency: string;
  /**
   * Amount in minor units (e.g. cents).
   */
  value: number;
};
