// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Mobile app settings
 */
export type AppSettings = {
  /**
   * Checkout preference
   */
  checkout_preference?: string;
  /**
   * Include vat.
   */
  include_vat?: boolean;
  /**
   * Manual entry tutorial.
   */
  manual_entry_tutorial?: boolean;
  /**
   * Mobile payment tutorial.
   */
  mobile_payment_tutorial?: boolean;
  /**
   * Tax enabled.
   */
  tax_enabled?: boolean;
  /**
   * Mobile payment.
   */
  mobile_payment?: string;
  /**
   * Reader payment.
   */
  reader_payment?: string;
  /**
   * Cash payment.
   */
  cash_payment?: string;
  /**
   * Advanced mode.
   */
  advanced_mode?: string;
  /**
   * Expected max transaction amount.
   */
  expected_max_transaction_amount?: number;
  /**
   * Manual entry.
   */
  manual_entry?: string;
  /**
   * Terminal mode tutorial.
   */
  terminal_mode_tutorial?: boolean;
  /**
   * Tipping.
   */
  tipping?: string;
  /**
   * Tip rates.
   */
  tip_rates?: number[];
  /**
   * Barcode scanner.
   */
  barcode_scanner?: string;
  /**
   * Referral.
   */
  referral?: string;
};
