// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * BadGateway
 *
 * 502 Bad Gateway
 */
export type BadGateway = {
  errors: {
    /**
     * Fuller message giving context to error
     */
    detail: string;
  };
};
