// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Bank Account Payload
 *
 * Bank account details used when creating or updating a payout account.
 */
export type BankAccountPayload = {
  /**
   * Bank code
   */
  bank_code?: string;
  /**
   * Branch code
   */
  branch_code?: string;
  /**
   * Account number
   */
  account_number?: string;
  /**
   * IBAN
   */
  iban: string;
  /**
   * SWIFT code
   */
  swift: string;
  /**
   * Type of the account.
   */
  account_type?: "CURRENT" | "SAVINGS";
  /**
   * Account holder name
   */
  account_holder_name: string;
  /**
   * Check digit
   */
  check_digit?: string;
  /**
   * Determines if this bank account will be primary. Default is false
   */
  primary?: boolean;
  /**
   * Determines the bank account status.
   */
  status?: "OPEN";
  /**
   * Determines if this bank account is business or personal.
   */
  account_category?: "PERSONAL" | "BUSINESS";
};
