// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Address } from "./address";
import type { ChangeStatus } from "./change-status";
import type { CountryCode } from "./country-code";
import type { Ownership } from "./ownership";
import type { PersonalIdentifiers } from "./personal-identifiers";
import type { PhoneNumber } from "./phone-number";
import type { Version } from "./version";

/**
 * Base schema for a Person associated with a Merchant. This can be a legal representative, business owner (ultimate beneficial owner), or an officer. A legal representative is the Person who registered the Merchant with SumUp. They should always have a `user_id`.
 *
 *
 * Person documentation: https://developer.sumup.com/tools/glossary/merchant#persons
 */
export type BasePerson = {
  /**
   * The unique identifier for the Person. This is a [typeid](https://github.com/sumup/typeid).
   *
   */
  readonly id: string;
  /**
   * A corresponding identity user ID for the Person, if they have a user account.
   *
   */
  user_id?: string;
  /**
   * The date of birth of the individual, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format.
   *
   */
  birthdate?: string;
  /**
   * The first name(s) of the individual.
   */
  given_name?: string;
  /**
   * The last name(s) of the individual.
   */
  family_name?: string;
  /**
   * Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; all can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used.
   *
   */
  middle_name?: string;
  phone_number?: PhoneNumber;
  /**
   * A list of roles the Person has in the Merchant or towards SumUp. A Merchant must have at least one Person with the relationship `representative`.
   *
   */
  relationships?: string[];
  ownership?: Ownership;
  address?: Address;
  identifiers?: PersonalIdentifiers;
  citizenship?: CountryCode;
  /**
   * The Person's nationality. May be an [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code, but legacy data may not conform to this standard.
   *
   */
  nationality?: string | null;
  /**
   * An [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code representing the country where the Person resides.
   *
   */
  country_of_residence?: string | null;
  version?: Version;
  change_status?: ChangeStatus;
};
