// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Settings used to apply the Merchant's branding to email receipts, invoices, checkouts, and other products.
 */
export type Branding = {
  /**
   * An icon for the merchant. Must be square.
   *
   */
  icon?: string;
  /**
   * A logo for the merchant that will be used in place of the icon and without the merchant's name next to it if there's sufficient space.
   *
   */
  logo?: string;
  /**
   * Data-URL encoded hero image for the merchant business.
   *
   */
  hero?: string;
  /**
   * A hex color value representing the primary branding color of this merchant (your brand color).
   *
   */
  primary_color?: string;
  /**
   * A hex color value representing the color of the text displayed on branding color of this merchant.
   *
   */
  primary_color_fg?: string;
  /**
   * A hex color value representing the secondary branding color of this merchant (accent color used for buttons).
   *
   */
  secondary_color?: string;
  /**
   * A hex color value representing the color of the text displayed on secondary branding color of this merchant.
   *
   */
  secondary_color_fg?: string;
  /**
   * A hex color value representing the preferred background color of this merchant.
   *
   */
  background_color?: string;
};
