// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Business owners information.
 */
export type BusinessOwners = {
  /**
   * BO's first name
   */
  first_name?: string;
  /**
   * BO's last name of the user
   */
  last_name?: string;
  /**
   * Date of birth
   */
  date_of_birth?: string;
  /**
   * Mobile phone number
   */
  mobile_phone?: string;
  /**
   * BO's Landline
   */
  landline?: string;
  /**
   * Ownership percentage
   */
  ownership?: number;
}[];
