// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Address } from "./address";
import type { Branding } from "./branding";
import type { PhoneNumber } from "./phone-number";

/**
 * Business information about the merchant. This information will be visible to the merchant's customers.
 *
 */
export type BusinessProfile = {
  /**
   * The customer-facing business name.
   */
  name?: string;
  /**
   * The descriptor is the text that your customer sees on their bank account statement.
   * The more recognisable your descriptor is, the less risk you have of receiving disputes (e.g. chargebacks).
   *
   */
  dynamic_descriptor?: string;
  /**
   * The business's publicly available website.
   */
  website?: string;
  /**
   * A publicly available email address.
   */
  email?: string;
  phone_number?: PhoneNumber;
  address?: Address;
  branding?: Branding;
};
