// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CardType } from "./card-type";

/**
 * Card Response
 *
 * Details of the payment card.
 */
export type CardResponse = {
  /**
   * Last 4 digits of the payment card number.
   */
  readonly last_4_digits?: string;
  type?: CardType;
  /**
   * PAR (Payment account reference) if available for the card.
   */
  payment_account_reference?: string;
};
