// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Issuing card network of the payment card used for the transaction.
 */
export type CardType =
  | "ALELO"
  | "AMEX"
  | "CONECS"
  | "CUP"
  | "DINERS"
  | "DISCOVER"
  | "EFTPOS"
  | "ELO"
  | "ELV"
  | "GIROCARD"
  | "HIPERCARD"
  | "INTERAC"
  | "JCB"
  | "MAESTRO"
  | "MASTERCARD"
  | "PLUXEE"
  | "SWILE"
  | "TICKET"
  | "VISA"
  | "VISA_ELECTRON"
  | "VISA_VPAY"
  | "VPAY"
  | "VR"
  | "UNKNOWN";
