// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CardType } from "./card-type";

/**
 * Card
 *
 * __Required when payment type is `card`.__ Details of the payment card.
 */
export type Card = {
  /**
   * Name of the cardholder as it appears on the payment card.
   */
  name: string;
  /**
   * Number of the payment card (without spaces).
   */
  number: string;
  /**
   * Two- or four-digit expiration year in `YY` or `YYYY` format.
   */
  expiry_year: string;
  /**
   * Two-digit expiration month, from `01` through `12`.
   */
  expiry_month: string;
  /**
   * Three or four-digit card verification value (security code) of the payment card.
   */
  cvv: string;
  /**
   * Required five-digit ZIP code. Applicable only to merchant users in the USA.
   */
  zip_code?: string;
  type: CardType;
};
