// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Reflects the status of changes submitted through the `PATCH` endpoints for the merchant or persons. If some changes have not been applied yet, the status will be `pending`. If all changes have been applied, the status `done`.
 * The status is only returned after write operations or on read endpoints when the `version` query parameter is provided.
 *
 */
export type ChangeStatus = string;
