// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Checkout Accepted
 *
 * Response returned when checkout processing requires an additional payer action, such as a 3DS challenge or a redirect to an external payment method page.
 */
export type CheckoutAccepted = {
  /**
   * Instructions for the next action the payer or client must take.
   */
  next_step?: {
    /**
     * URL to open or submit in order to continue processing.
     */
    url?: string;
    /**
     * HTTP method to use when following the next step.
     */
    method?: string;
    /**
     * Merchant URL where the payer returns after the external flow finishes.
     */
    redirect_url?: string;
    /**
     * Allowed presentation mechanisms for the next step. `iframe` means the flow can be embedded, while `browser` means it can be completed through a full-page redirect.
     */
    mechanism?: ("iframe" | "browser")[];
    /**
     * Parameters required to complete the next step. The exact keys depend on the payment provider and flow type.
     */
    payload?: Record<string, string>;
  };
};
