// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Currency } from "./currency";
import type { MandateResponse } from "./mandate-response";
import type { TransactionBase } from "./transaction-base";
import type { TransactionCheckoutInfo } from "./transaction-checkout-info";

/**
 * Checkout
 *
 * Details of the payment checkout.
 */
export type Checkout = {
  /**
   * Unique ID of the payment checkout specified by the client application when creating the checkout resource.
   */
  checkout_reference?: string;
  /**
   * Amount of the payment.
   */
  amount?: number;
  currency?: Currency;
  /**
   * Unique identifying code of the merchant profile.
   */
  merchant_code?: string;
  /**
   * Short description of the checkout visible in the SumUp dashboard. The description can contribute to reporting, allowing easier identification of a checkout.
   */
  description?: string;
  /**
   * URL to which the SumUp platform sends the processing status of the payment checkout.
   */
  return_url?: string;
  /**
   * Unique ID of the checkout resource.
   */
  id?: string;
  /**
   * Current status of the checkout.
   */
  status?: "PENDING" | "FAILED" | "PAID" | "EXPIRED";
  /**
   * Date and time of the creation of the payment checkout. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.
   */
  date?: string;
  /**
   * Date and time of the checkout expiration before which the client application needs to send a processing request. If no value is present, the checkout does not have an expiration time.
   */
  valid_until?: string | null;
  /**
   * Unique identification of a customer. If specified, the checkout session and payment instrument are associated with the referenced customer.
   */
  customer_id?: string;
  mandate?: MandateResponse;
  /**
   * List of transactions related to the payment.
   */
  transactions?: (TransactionBase & TransactionCheckoutInfo)[];
};
