// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Checkout } from "./checkout";

/**
 * Checkout Success
 *
 * Checkout resource returned after a synchronous processing attempt. In addition to the base checkout fields, it can include the resulting transaction identifiers and any newly created payment instrument token.
 */
export type CheckoutSuccess = Checkout & {
  /**
   * Transaction code of the successful transaction with which the payment for the checkout is completed.
   */
  readonly transaction_code?: string;
  /**
   * Transaction ID of the successful transaction with which the payment for the checkout is completed.
   */
  readonly transaction_id?: string;
  /**
   * Name of the merchant
   */
  merchant_name?: string;
  /**
   * URL where the payer is redirected after a redirect-based payment or SCA flow completes.
   */
  redirect_url?: string;
  /**
   * Details of the saved payment instrument created or reused during checkout processing.
   */
  payment_instrument?: {
    /**
     * Token value
     */
    token?: string;
  };
};
