// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Checkout } from "./checkout";

export type CheckoutSuccess = Checkout & {
  /**
   * Transaction code of the successful transaction with which the payment for the checkout is completed.
   */
  readonly transaction_code?: string;
  /**
   * Transaction ID of the successful transaction with which the payment for the checkout is completed.
   */
  readonly transaction_id?: string;
  /**
   * Name of the merchant
   */
  merchant_name?: string;
  /**
   * Refers to a url where the end user is redirected once the payment processing completes.
   */
  redirect_url?: string;
  /**
   * Object containing token information for the specified payment instrument
   */
  payment_instrument?: {
    /**
     * Token value
     */
    token?: string;
  };
};
