// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * 3DS Response
 */
export type CheckoutAccepted = {
  /**
   * Required action processing 3D Secure payments.
   */
  next_step?: {
    /**
     * Where the end user is redirected.
     */
    url?: string;
    /**
     * Method used to complete the redirect.
     */
    method?: string;
    /**
     * Refers to a url where the end user is redirected once the payment processing completes.
     */
    redirect_url?: string;
    /**
     * Indicates allowed mechanisms for redirecting an end user. If both values are provided to ensure a redirect takes place in either.
     */
    mechanism?: ("iframe" | "browser")[];
    /**
     * Contains parameters essential for form redirection. Number of object keys and their content can vary.
     */
    payload?: {
      PaReq?: Record<string, unknown>;
      MD?: Record<string, unknown>;
      TermUrl?: Record<string, unknown>;
    };
  };
};
