// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Currency } from "./currency";

/**
 * Checkout Update Request
 *
 * Request body for updating an existing checkout. Include only the fields that should be changed.
 */
export type CheckoutUpdateRequest = {
  /**
   * Updated amount to be charged to the payer, expressed in major units.
   */
  amount?: number;
  currency?: Currency;
  /**
   * Updated short merchant-defined description shown in SumUp tools and reporting.
   */
  description?: string;
  /**
   * Updated merchant-defined reference for the checkout.
   */
  checkout_reference?: string;
  /**
   * Updated expiration timestamp. The checkout must be processed before this moment, otherwise it becomes unusable.
   */
  valid_until?: string | null;
  /**
   * Updated merchant-scoped customer identifier associated with the checkout.
   */
  customer_id?: string;
};
