// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Address } from "./address";
import type { Attributes } from "./attributes";
import type { CompanyIdentifiers } from "./company-identifiers";
import type { LegalType } from "./legal-type";
import type { PhoneNumber } from "./phone-number";

/**
 * Information about the company or business. This is legal information that is used for verification.
 *
 *
 * Company documentation: https://developer.sumup.com/tools/models/merchant#company
 */
export type Company = {
  /**
   * The company's legal name.
   */
  name?: string;
  /**
   * The merchant category code for the account as specified by [ISO18245](https://www.iso.org/standard/33365.html). MCCs are used to classify businesses based on the goods or services they provide.
   *
   */
  merchant_category_code?: string;
  legal_type?: LegalType;
  address?: Address;
  trading_address?: Address;
  identifiers?: CompanyIdentifiers;
  phone_number?: PhoneNumber;
  /**
   * HTTP(S) URL of the company's website.
   *
   */
  website?: string | null;
  attributes?: Attributes;
};
