// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CompanyIdentifier } from "./company-identifier";

/**
 * A list of country-specific company identifiers.
 *
 */
export type CompanyIdentifiers = CompanyIdentifier[];
