// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type CompanyIdentifier = {
  /**
   * The unique reference for the company identifier type as defined in the country SDK.
   *
   */
  ref: string;
  /**
   * The company identifier value.
   *
   */
  value: string;
};
