// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * An [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
 * country code. This definition users `oneOf` with a two-character string
 * type to allow for support of future countries in client code.
 */
export type CountryCode = string;
