// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * CreateReaderCheckoutResponse
 */
export type CreateReaderCheckoutResponse = {
  data: {
    /**
     * The client transaction ID is a unique identifier for the transaction that is generated for the client.
     *
     * It can be used later to fetch the transaction details via the [Transactions API](https://developer.sumup.com/api/transactions/get).
     *
     */
    client_transaction_id: string;
  };
};
