// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * CreateReaderCheckoutUnprocessableEntity
 *
 * Unprocessable entity
 */
export type CreateReaderCheckoutUnprocessableEntity = {
  errors: Record<string, unknown>;
};
