// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * CreateReaderCheckoutError
 *
 * Error description
 */
export type CreateReaderCheckoutError = {
  errors: {
    /**
     * Error message
     */
    detail?: string;
  };
};
