// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { PersonalDetails } from "./personal-details";

/**
 * Customer
 */
export type Customer = {
  /**
   * Unique ID of the customer.
   */
  customer_id: string;
  personal_details?: PersonalDetails;
};
