// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Details Error
 *
 * Details of a request validation error.
 */
export type DetailsError = {
  /**
   * Short title of the error.
   */
  title?: string;
  /**
   * Details of the error.
   */
  details?: string;
  /**
   * HTTP status code for the error.
   */
  status?: number;
  /**
   * List of violated validation constraints.
   */
  failed_constraints?: {
    /**
     * Human-readable description of the violated constraint.
     */
    message?: string;
    /**
     * Name of the field that violated the constraint.
     */
    reference?: string;
  }[];
};
