// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Details Error
 *
 * Error message structure.
 */
export type DetailsError = {
  /**
   * Short title of the error.
   */
  title?: string;
  /**
   * Details of the error.
   */
  details?: string;
  /**
   * The status code.
   */
  status?: number;
  /**
   * List of violated validation constraints.
   */
  failed_constraints?: { message?: string; reference?: string }[];
};
