// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type Device = {
  /**
   * Device name.
   */
  name?: string;
  /**
   * Device OS.
   */
  system_name?: string;
  /**
   * Device model.
   */
  model?: string;
  /**
   * Device OS version.
   */
  system_version?: string;
  /**
   * Device UUID.
   */
  uuid?: string;
};
