// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Doing Business As information
 */
export type DoingBusinessAsLegacy = {
  /**
   * Doing business as name
   */
  business_name?: string;
  /**
   * Doing business as company registration number
   */
  company_registration_number?: string;
  /**
   * Doing business as VAT ID
   */
  vat_id?: string;
  /**
   * Doing business as website
   */
  website?: string;
  /**
   * Doing business as email
   */
  email?: string;
  address?: {
    /**
     * Address line 1
     */
    address_line1?: string;
    /**
     * Address line 2
     */
    address_line2?: string;
    /**
     * City
     */
    city?: string;
    /**
     * Country ISO 3166-1 code
     */
    country?: string;
    /**
     * Country region ID
     */
    region_id?: number;
    /**
     * Country region name
     */
    region_name?: string;
    /**
     * Postal code
     */
    post_code?: string;
  };
};
