// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { AddressPayloadLegacy } from "./address-payload-legacy";

/**
 * Doing Business As information
 */
export type DoingBusinessAsPayloadLegacy = {
  /**
   * Doing business as name
   */
  business_name?: string;
  /**
   * Doing business as Tax ID
   */
  tax_id?: string;
  /**
   * Doing business as VAT ID
   */
  vat_id?: string;
  /**
   * Doing business as website
   */
  website?: string;
  /**
   * Doing business as email
   */
  email?: string;
  address?: AddressPayloadLegacy;
};
