// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * ELV Card Account
 *
 * Details of the ELV card account associated with the transaction.
 */
export type ElvCardAccount = {
  /**
   * ELV card sort code.
   */
  sort_code?: string;
  /**
   * ELV card account number last 4 digits.
   */
  last_4_digits?: string;
  /**
   * ELV card sequence number.
   */
  sequence_no?: number;
  /**
   * ELV IBAN.
   */
  iban?: string;
};
