// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Entry mode of the payment details.
 */
export type EntryMode =
  | "none"
  | "magstripe"
  | "chip"
  | "manual entry"
  | "customer entry"
  | "magstripe fallback"
  | "contactless"
  | "moto"
  | "contactless magstripe"
  | "boleto"
  | "direct debit"
  | "sofort"
  | "ideal"
  | "bancontact"
  | "eps"
  | "mybank"
  | "satispay"
  | "blik"
  | "p24"
  | "giropay"
  | "pix"
  | "qr code pix"
  | "apple pay"
  | "google pay"
  | "paypal"
  | "na";
