// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Entry Mode
 *
 * Entry mode of the payment details.
 */
export type EntryMode =
  | "BOLETO"
  | "SOFORT"
  | "IDEAL"
  | "BANCONTACT"
  | "EPS"
  | "MYBANK"
  | "SATISPAY"
  | "BLIK"
  | "P24"
  | "GIROPAY"
  | "PIX"
  | "QR_CODE_PIX"
  | "APPLE_PAY"
  | "GOOGLE_PAY"
  | "PAYPAL"
  | "TWINT"
  | "NONE"
  | "CHIP"
  | "MANUAL_ENTRY"
  | "CUSTOMER_ENTRY"
  | "MAGSTRIPE_FALLBACK"
  | "MAGSTRIPE"
  | "DIRECT_DEBIT"
  | "CONTACTLESS"
  | "MOTO"
  | "CONTACTLESS_MAGSTRIPE"
  | "N/A";
