// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Error
 *
 * Details of an API error.
 */
export type ErrorBody = {
  /**
   * Short description of the error.
   */
  message?: string;
  /**
   * Platform code for the error.
   */
  error_code?: string;
};
