// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { TransactionEventID } from "./transaction-event-id";
import type { TransactionEventStatus } from "./transaction-event-status";
import type { TransactionEventType } from "./transaction-event-type";
import type { TransactionID } from "./transaction-id";

/**
 * Event
 *
 * High-level transaction event details.
 */
export type Event = {
  id?: TransactionEventID;
  transaction_id?: TransactionID;
  type?: TransactionEventType;
  status?: TransactionEventStatus;
  /**
   * Amount associated with the transaction event, in major units.
   */
  amount?: number;
  /**
   * The timestamp of when the transaction event occurred.
   */
  timestamp?: string;
  /**
   * Fee associated with the transaction event, in major units.
   */
  fee_amount?: number;
  /**
   * Consecutive number of the installment associated with the event.
   */
  installment_number?: number;
  /**
   * Amount deducted from the merchant for the event, in major units.
   */
  deducted_amount?: number;
  /**
   * Fee deducted from the merchant for the event, in major units.
   */
  deducted_fee_amount?: number;
};
