// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { TransactionEventID } from "./transaction-event-id";
import type { TransactionEventStatus } from "./transaction-event-status";
import type { TransactionEventType } from "./transaction-event-type";
import type { TransactionID } from "./transaction-id";

/**
 * Event
 *
 * High-level transaction event details.
 */
export type Event = {
  id?: TransactionEventID;
  transaction_id?: TransactionID;
  type?: TransactionEventType;
  status?: TransactionEventStatus;
  /**
   * Amount of the event.
   */
  amount?: number;
  /**
   * Date and time of the transaction event.
   */
  timestamp?: string;
  /**
   * Amount of the fee related to the event.
   */
  fee_amount?: number;
  /**
   * Consecutive number of the installment.
   */
  installment_number?: number;
  /**
   * Amount deducted for the event.
   */
  deducted_amount?: number;
  /**
   * Amount of the fee deducted for the event.
   */
  deducted_fee_amount?: number;
};
