// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Event Status
 *
 * Status of the transaction event.
 */
export type EventStatus =
  | "FAILED"
  | "PAID_OUT"
  | "PENDING"
  | "RECONCILED"
  | "REFUNDED"
  | "SCHEDULED"
  | "SUCCESSFUL";
