// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Financial Payout
 *
 * A single payout-related record.
 *
 * A record can represent either:
 * - an actual payout sent to the merchant (`type = PAYOUT`)
 * - a deduction applied against merchant funds for a refund, chargeback, direct debit return, or balance adjustment
 */
export type FinancialPayout = {
  /**
   * Unique identifier of the payout-related record.
   */
  id: number;
  /**
   * High-level payout record category.
   */
  type:
    | "PAYOUT"
    | "CHARGE_BACK_DEDUCTION"
    | "REFUND_DEDUCTION"
    | "DD_RETURN_DEDUCTION"
    | "BALANCE_DEDUCTION";
  /**
   * Amount of the payout or deduction in major units.
   */
  amount: number;
  /**
   * Payout date associated with the record, in `YYYY-MM-DD` format.
   */
  date: string;
  /**
   * Three-letter ISO 4217 currency code of the payout.
   */
  currency: string;
  /**
   * Fee amount associated with the payout record, in major units.
   */
  fee: number;
  /**
   * Merchant-facing outcome of the payout record.
   */
  status: "SUCCESSFUL" | "FAILED";
  /**
   * Processor or payout reference associated with the record.
   */
  reference: string;
  /**
   * Transaction code of the original sale associated with the payout or deduction.
   */
  transaction_code: string;
};
