// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { FinancialPayout } from "./financial-payout";

/**
 * Financial Payouts
 *
 * Ordered list of payout and payout-deduction records.
 */
export type FinancialPayouts = FinancialPayout[];
