// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Financial Payouts
 */
export type FinancialPayouts = {
  amount?: number;
  currency?: string;
  date?: string;
  fee?: number;
  id?: number;
  reference?: string;
  status?: "SUCCESSFUL" | "FAILED";
  transaction_code?: string;
  type?:
    | "PAYOUT"
    | "CHARGE_BACK_DEDUCTION"
    | "REFUND_DEDUCTION"
    | "DD_RETURN_DEDUCTION"
    | "BALANCE_DEDUCTION";
}[];
