// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Indication of the precision of the geographical position received from the payment terminal.
 */
export type HorizontalAccuracy = number;
