// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Hosted Checkout
 *
 * Hosted Checkout configuration. Enable it to receive a SumUp-hosted payment page URL in the checkout response.
 */
export type HostedCheckout = {
  /**
   * Whether the checkout should include a SumUp-hosted payment page.
   */
  enabled: boolean;
};
