// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * InternalServerError
 *
 * 500 Internal Server Error
 */
export type InternalServerError = {
  errors: {
    /**
     * Fuller message giving context to error
     */
    detail: string;
  };
};
