// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Invite
 *
 * Pending invitation for membership.
 */
export type Invite = {
  /**
   * Email address of the invited user.
   */
  email: string;
  expires_at: string;
};
