// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Latitude value from the coordinates of the payment location (as received from the payment terminal reader).
 */
export type Lat = number;
