// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * The unique legal type reference as defined in the country SDK. We do not rely on IDs as used by other services. Consumers of this API are expected to use the country SDK to map to any other IDs, translation keys, or descriptions.
 *
 *
 * The country SDK documentation for legal types.: https://developer.sumup.com/tools/models/merchant#legal-types
 */
export type LegalType = string;
