// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Id of the legal type of the merchant profile
 */
export type LegalTypeLegacy = {
  /**
   * Unique id
   */
  id?: number;
  /**
   * Legal type description
   */
  full_description?: string;
  /**
   * Legal type short description
   */
  description?: string;
  /**
   * Sole trader legal type if true
   */
  sole_trader?: boolean;
};
