// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Link } from "./link";

export type LinkRefund = Link & {
  /**
   * Minimum allowed amount for the refund.
   */
  min_amount?: number;
  /**
   * Maximum allowed amount for the refund.
   */
  max_amount?: number;
};
