// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Details of a link to a related resource.
 */
export type Link = {
  /**
   * Specifies the relation to the current resource.
   */
  rel?: string;
  /**
   * URL for accessing the related resource.
   */
  href?: string;
  /**
   * Specifies the media type of the related resource.
   */
  type?: string;
};
