// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Link
 *
 * Details of a link to a related resource.
 */
export type Link = {
  /**
   * Relation of the linked resource to the current resource.
   */
  rel?: string;
  /**
   * URL for accessing the related resource.
   */
  href?: string;
  /**
   * Media type of the linked resource.
   */
  type?: string;
  /**
   * Minimum amount allowed for a refund, in major units.
   */
  min_amount?: number;
  /**
   * Maximum amount allowed for a refund, in major units.
   */
  max_amount?: number;
};
