// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Mandate Payload
 *
 * Mandate details used when a checkout should create a reusable card token for future recurring or merchant-initiated payments.
 */
export type MandatePayload = {
  /**
   * Type of mandate to create for the saved payment instrument.
   */
  type: "recurrent";
  /**
   * Browser or client user agent observed when consent was collected.
   */
  user_agent: string;
  /**
   * IP address of the payer when the mandate was accepted.
   */
  user_ip?: string;
};
