// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Mandate Response
 *
 * Details of the mandate linked to the saved payment instrument.
 */
export type MandateResponse = {
  /**
   * Type of mandate stored for the checkout or payment instrument.
   */
  type?: string;
  /**
   * Current lifecycle status of the mandate.
   */
  status?: "active" | "inactive";
  /**
   * Merchant account for which the mandate is valid.
   */
  merchant_code?: string;
};
