// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Mandate is passed when a card is to be tokenized
 */
export type MandatePayload = {
  /**
   * Indicates the mandate type
   */
  type: "recurrent";
  /**
   * Operating system and web client used by the end-user
   */
  user_agent: string;
  /**
   * IP address of the end user. Supports IPv4 and IPv6
   */
  user_ip?: string;
};
