// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Attributes } from "./attributes";
import type { ResourceType } from "./resource-type";

/**
 * Resource
 *
 * Information about the resource the membership is in.
 */
export type MembershipResource = {
  /**
   * ID of the resource the membership is in.
   */
  id: string;
  type: ResourceType;
  /**
   * Display name of the resource.
   */
  name: string;
  /**
   * Logo fo the resource.
   */
  logo?: string;
  /**
   * The timestamp of when the membership resource was created.
   */
  created_at: string;
  /**
   * The timestamp of when the membership resource was last updated.
   */
  updated_at: string;
  attributes?: Attributes;
};
