// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { MembershipUserClassic } from "./membership-user-classic";

/**
 * Information about the user associated with the membership.
 */
export type MembershipUser = {
  /**
   * Identifier for the End-User (also called Subject).
   */
  id: string;
  /**
   * End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, for unique identification use ID instead.
   */
  email: string;
  /**
   * True if the user has enabled MFA on login.
   */
  mfa_on_login_enabled: boolean;
  /**
   * True if the user is a virtual user (operator).
   */
  virtual_user: boolean;
  /**
   * True if the user is a service account.
   */
  service_account_user: boolean;
  /**
   * Time when the user has been disabled. Applies only to virtual users (`virtual_user: true`).
   */
  disabled_at?: string;
  /**
   * User's preferred name. Used for display purposes only.
   */
  nickname?: string;
  /**
   * URL of the End-User's profile picture. This URL refers to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image.
   */
  picture?: string;
  classic?: MembershipUserClassic;
};
