// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { AddressPayloadLegacy } from "./address-payload-legacy";
import type { BusinessOwners } from "./business-owners";

/**
 * Account's merchant profile
 */
export type MerchantProfilePayload = {
  /**
   * Id of the legal type of the merchant
   */
  legal_type_id: number;
  /**
   * Merchant category code
   */
  merchant_category_code: string;
  /**
   * Company name
   */
  company_name: string;
  /**
   * Company registration number
   */
  company_registration_number: string;
  /**
   * Vat ID
   */
  vat_id?: string;
  /**
   * Payment certificate access code
   */
  permanent_certificate_access_code?: string;
  /**
   * Company website
   */
  website?: string;
  /**
   * Nature and purpose of the business. Required for the following merchant category codes: 5999, 7392, 8999, 5694, 5969, 7299, 7399
   */
  nature_and_purpose?: string;
  /**
   * Mobile number
   */
  mobile_phone?: string;
  address: AddressPayloadLegacy;
  doing_business_as?: {
    /**
     * Doing business as name
     */
    business_name?: string;
    /**
     * Doing business as Tax ID
     */
    tax_id?: string;
    /**
     * Doing business as Vat ID
     */
    vat_id?: string;
    /**
     * Doing business as website
     */
    website?: string;
    /**
     * Doing business as email
     */
    email?: string;
    address?: AddressPayloadLegacy;
  };
  business_owners?: BusinessOwners;
  /**
   * Defines if the profile nature is for testing
   */
  is_test_account?: boolean;
};
