// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type MerchantSettingsPayload = {
  /**
   * Payout period.
   */
  payout_period?: "daily" | "weekly" | "monthly";
  /**
   * Payout type.
   */
  payout_type?: "SINGLE_PAYMENT";
  /**
   * If true, the merchant will not receive automatic payouts.
   */
  payout_on_demand?: boolean;
  /**
   * If true, the merchant will be able to manage  payout_on_demand settings
   */
  payout_on_demand_available?: string;
  /**
   * Expected maximum amount of a single purchase
   */
  expected_max_transaction_amount?: number;
  /**
   * Printers enabled.
   */
  printers_enabled?: boolean;
  /**
   * Gross settlement
   */
  gross_settlement?: boolean;
};
