// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { AccountLegacy } from "./account-legacy";
import type { AppSettings } from "./app-settings";
import type { MerchantProfileLegacy } from "./merchant-profile-legacy";
import type { PermissionsLegacy } from "./permissions-legacy";
import type { PersonalProfileLegacy } from "./personal-profile-legacy";

/**
 * Merchant Account
 *
 * Details of the merchant account.
 */
export type MerchantAccount = {
  account?: AccountLegacy;
  personal_profile?: PersonalProfileLegacy;
  merchant_profile?: MerchantProfileLegacy;
  app_settings?: AppSettings;
  permissions?: PermissionsLegacy;
};
