// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { AddressWithDetails } from "./address-with-details";
import type { BankAccount } from "./bank-account";
import type { BusinessOwners } from "./business-owners";
import type { DoingBusinessAsLegacy } from "./doing-business-as-legacy";
import type { LegalTypeLegacy } from "./legal-type-legacy";
import type { MerchantSettings } from "./merchant-settings";
import type { VatRates } from "./vat-rates";

/**
 * Account's merchant profile
 */
export type MerchantProfileLegacy = {
  /**
   * Unique identifying code of the merchant profile
   */
  merchant_code?: string;
  /**
   * Company name
   */
  company_name?: string;
  /**
   * Website
   */
  website?: string;
  legal_type?: LegalTypeLegacy;
  /**
   * Merchant category code
   */
  merchant_category_code?: string;
  /**
   * Mobile phone number
   */
  mobile_phone?: string;
  /**
   * Company registration number
   */
  company_registration_number?: string;
  /**
   * Vat ID
   */
  vat_id?: string;
  /**
   * Permanent certificate access code &#40;Portugal&#41;
   */
  permanent_certificate_access_code?: string;
  /**
   * Nature and purpose of the business
   */
  nature_and_purpose?: string;
  address?: AddressWithDetails;
  business_owners?: BusinessOwners;
  doing_business_as?: DoingBusinessAsLegacy;
  settings?: MerchantSettings;
  vat_rates?: VatRates;
  /**
   * Merchant locale &#40;for internal usage only&#41;
   */
  locale?: string;
  bank_accounts?: BankAccount[];
  /**
   * True if the merchant is extdev
   */
  extdev?: boolean;
  /**
   * True if the payout zone of this merchant is migrated
   */
  payout_zone_migrated?: boolean;
  /**
   * Merchant country code formatted according to [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) &#40;for internal usage only&#41;
   */
  country?: string;
};
