// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Merchant settings &#40;like \"payout_type\", \"payout_period\"&#41;
 */
export type MerchantSettings = {
  /**
   * Whether to show tax in receipts &#40;saved per transaction&#41;
   */
  tax_enabled?: boolean;
  /**
   * Payout type
   */
  payout_type?: string;
  /**
   * Payout frequency
   */
  payout_period?: string;
  /**
   * Whether merchant can edit payouts on demand
   */
  payout_on_demand_available?: boolean;
  /**
   * Whether merchant will receive payouts on demand
   */
  payout_on_demand?: boolean;
  /**
   * Whether to show printers in mobile app
   */
  printers_enabled?: boolean;
  /**
   * Payout Instrument
   */
  payout_instrument?: string;
  /**
   * Whether merchant can make MOTO payments
   */
  moto_payment?: "UNAVAILABLE" | "ENFORCED" | "ON" | "OFF";
  /**
   * Stone merchant code
   */
  stone_merchant_code?: string;
  /**
   * Whether merchant will receive daily payout emails
   */
  daily_payout_email?: boolean;
  /**
   * Whether merchant will receive monthly payout emails
   */
  monthly_payout_email?: boolean;
  /**
   * Whether merchant has gross settlement enabled
   */
  gross_settlement?: boolean;
};
