// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * NotFound
 *
 * 404 Not Found
 */
export type NotFound = {
  errors: {
    /**
     * Fuller message giving context to error
     */
    detail: string;
  };
};
