// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Permissions } from "./permissions";

/**
 * Operator account for a merchant.
 */
export type Operator = {
  id: number;
  username: string;
  nickname?: string | null;
  disabled: boolean;
  /**
   * The timestamp of when the operator was created.
   */
  created_at: string;
  /**
   * The timestamp of when the operator was last updated.
   */
  updated_at: string;
  permissions: Permissions;
  account_type: "operator" | "normal";
};
