// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type Ownership = {
  /**
   * The percent of ownership shares held by the Person expressed in percent mille (1/100000). Only Persons with the relationship `owner` can have ownership.
   *
   */
  share: number;
};
