// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Payment Type
 *
 * Payment category recorded on a transaction, for example `POS` for a point-of-sale card payment, `ECOM` for an online card payment, or `RECURRING` for a recurring card payment. These reporting values are separate from the lowercase `payment_type` values used to process checkouts.
 */
export type PaymentType =
  | "CASH"
  | "POS"
  | "ECOM"
  | "RECURRING"
  | "BITCOIN"
  | "BALANCE"
  | "MOTO"
  | "BOLETO"
  | "DIRECT_DEBIT"
  | "APM"
  | "UNKNOWN";
