// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CardType } from "./card-type";
import type { MandateResponse } from "./mandate-response";

/**
 * Payment Instrument Response
 *
 * Details of a saved payment instrument.
 */
export type PaymentInstrumentResponse = {
  /**
   * Token identifying the customer's saved payment card. Pass it as `token`, together with the associated `customer_id` and `payment_type = card`, when processing a checkout with this instrument.
   */
  readonly token?: string;
  /**
   * Indicates whether the payment instrument is active and can be used for payments. To deactivate it, send a `DELETE` request to the resource endpoint.
   */
  readonly active?: boolean;
  /**
   * Type of the payment instrument.
   */
  type?: "card";
  /**
   * Details of the payment card.
   */
  card?: {
    /**
     * Last 4 digits of the payment card number.
     */
    readonly last_4_digits?: string;
    type?: CardType;
  };
  mandate?: MandateResponse;
  /**
   * The timestamp of when the payment instrument was created.
   */
  created_at?: string;
};
