// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Card } from "./card";

/**
 * Payment Instrument Card
 *
 * Details of the payment card that is saved as a payment instrument.
 */
export type PaymentInstrumentCard = {
  /**
   * Type of the payment instrument.
   */
  type: "card";
  card: Card;
};
