// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Payment type used for the transaction.
 */
export type PaymentType =
  | "CASH"
  | "POS"
  | "ECOM"
  | "RECURRING"
  | "BITCOIN"
  | "BALANCE"
  | "MOTO"
  | "BOLETO"
  | "DIRECT_DEBIT"
  | "APM"
  | "UNKNOWN";
