// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * User permissions
 */
export type PermissionsLegacy = {
  /**
   * Create MOTO payments
   */
  create_moto_payments?: boolean;
  /**
   * Can view full merchant transaction history
   */
  full_transaction_history_view?: boolean;
  /**
   * Refund transactions
   */
  refund_transactions?: boolean;
  /**
   * Create referral
   */
  create_referral?: boolean;
};
