// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Permissions assigned to an operator or user.
 */
export type Permissions = {
  create_moto_payments: boolean;
  create_referral: boolean;
  full_transaction_history_view: boolean;
  refund_transactions: boolean;
  admin: boolean;
};
