// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type PersonalIdentifier = {
  /**
   * The unique reference for the personal identifier type.
   */
  ref: string;
  /**
   * The company identifier value.
   */
  value: string;
};
