// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type PersonalIdentifier = {
  /**
   * The unique reference for the personal identifier type as defined in the country SDK.
   *
   */
  ref: string;
  /**
   * The value of the personal identifier.
   *
   */
  value: string;
};
