// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { AddressWithDetails } from "./address-with-details";

/**
 * Account's personal profile.
 */
export type PersonalProfileLegacy = {
  /**
   * First name of the user
   */
  first_name?: string;
  /**
   * Last name of the user
   */
  last_name?: string;
  /**
   * Date of birth
   */
  date_of_birth?: string;
  /**
   * Mobile phone number
   */
  mobile_phone?: string;
  address?: AddressWithDetails;
  complete?: boolean;
};
