// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { AddressPayloadLegacy } from "./address-payload-legacy";

/**
 * Account's personal profile.
 */
export type PersonalProfilePayloadLegacy = {
  /**
   * First name of the user
   */
  first_name: string;
  /**
   * Last name of the user
   */
  last_name: string;
  /**
   * Date of birth
   */
  date_of_birth: string;
  /**
   * Mobile phone number
   */
  mobile_phone?: string;
  /**
   * National identification id. Country specific. Ex CPF &#40;Brazil&#41;, DNI (Spain), PESEL (Poland)
   */
  national_id?: string;
  address: AddressPayloadLegacy;
};
