// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { PersonalIdentifier } from "./personal-identifier";

/**
 * A list of country-specific personal identifiers.
 *
 */
export type PersonalIdentifiers = PersonalIdentifier[];
