// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { AddressLegacy } from "./address-legacy";

/**
 * Personal Details
 *
 * Personal details for the customer.
 */
export type PersonalDetails = {
  /**
   * First name of the customer.
   */
  first_name?: string;
  /**
   * Last name of the customer.
   */
  last_name?: string;
  /**
   * Email address of the customer.
   */
  email?: string;
  /**
   * Phone number of the customer.
   */
  phone?: string;
  /**
   * Date of birth of the customer.
   */
  birth_date?: string;
  /**
   * Identification number used for tax purposes, such as a CPF in Brazil.
   */
  tax_id?: string;
  address?: AddressLegacy;
};
