// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Card } from "./card";
import type { MandatePayload } from "./mandate-payload";
import type { PersonalDetails } from "./personal-details";

/**
 * Process Checkout
 *
 * Request body for attempting payment on an existing checkout. The required companion fields depend on the selected `payment_type`, for example card details, saved-card data, or payer information required by a specific payment method.
 */
export type ProcessCheckout = {
  /**
   * Payment method used for this processing attempt. It determines which additional request fields are required.
   */
  payment_type:
    | "card"
    | "boleto"
    | "ideal"
    | "blik"
    | "bancontact"
    | "google_pay"
    | "apple_pay";
  /**
   * Number of installments for deferred payments. Available only to merchant users in Brazil.
   */
  installments?: number;
  mandate?: MandatePayload;
  card?: Card;
  /**
   * Raw `PaymentData` object received from Google Pay. Send the Google Pay response payload as-is.
   */
  google_pay?: Record<string, unknown>;
  /**
   * Raw payment token object received from Apple Pay. Send the Apple Pay response payload as-is.
   */
  apple_pay?: Record<string, unknown>;
  /**
   * Saved-card token to use instead of raw card details when processing with a previously stored payment instrument.
   */
  token?: string;
  /**
   * Customer identifier associated with the saved payment instrument. Required when `token` is provided.
   */
  customer_id?: string;
  personal_details?: PersonalDetails;
};
