// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Card } from "./card";
import type { MandatePayload } from "./mandate-payload";
import type { PersonalDetails } from "./personal-details";

/**
 * Process Checkout
 *
 * Details of the payment instrument for processing the checkout.
 */
export type ProcessCheckout = {
  /**
   * Describes the payment method used to attempt processing
   */
  payment_type:
    | "card"
    | "boleto"
    | "ideal"
    | "blik"
    | "bancontact"
    | "google_pay"
    | "apple_pay";
  /**
   * Number of installments for deferred payments. Available only to merchant users in Brazil.
   */
  installments?: number;
  mandate?: MandatePayload;
  card?: Card;
  /**
   * Raw `PaymentData` object received from Google Pay. Send the Google Pay response payload as-is.
   */
  google_pay?: Record<string, unknown>;
  /**
   * Raw payment token object received from Apple Pay. Send the Apple Pay response payload as-is.
   */
  apple_pay?: Record<string, unknown>;
  /**
   * __Required when using a tokenized card to process a checkout.__ Unique token identifying the saved payment card for a customer.
   */
  token?: string;
  /**
   * __Required when `token` is provided.__ Unique ID of the customer.
   */
  customer_id?: string;
  personal_details?: PersonalDetails;
};
