// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Purchase product.
 */
export type Product = {
  /**
   * Product name.
   */
  name?: string;
  /**
   * Product description.
   */
  price_label?: string;
  /**
   * Product price.
   */
  price?: number;
  /**
   * VAT percentage.
   */
  vat_rate?: number;
  /**
   * VAT amount for a single product.
   */
  single_vat_amount?: number;
  /**
   * Product price incl. VAT.
   */
  price_with_vat?: number;
  /**
   * VAT amount.
   */
  vat_amount?: number;
  /**
   * Product quantity.
   */
  quantity?: number;
  /**
   * Quantity x product price.
   */
  total_price?: number;
  /**
   * Total price incl. VAT.
   */
  total_with_vat?: number;
};
