// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Details of the product for which the payment is made.
 */
export type Product = {
  /**
   * Name of the product from the merchant's catalog.
   */
  name?: string;
  /**
   * Price of the product without VAT.
   */
  price?: number;
  /**
   * VAT rate applicable to the product.
   */
  vat_rate?: number;
  /**
   * Amount of the VAT for a single product item (calculated as the product of `price` and `vat_rate`, i.e. `single_vat_amount = price * vat_rate`).
   */
  single_vat_amount?: number;
  /**
   * Price of a single product item with VAT.
   */
  price_with_vat?: number;
  /**
   * Total VAT amount for the purchase (calculated as the product of `single_vat_amount` and `quantity`, i.e. `vat_amount = single_vat_amount * quantity`).
   */
  vat_amount?: number;
  /**
   * Number of product items for the purchase.
   */
  quantity?: number;
  /**
   * Total price of the product items without VAT (calculated as the product of `price` and `quantity`, i.e. `total_price = price * quantity`).
   */
  total_price?: number;
  /**
   * Total price of the product items including VAT (calculated as the product of `price_with_vat` and `quantity`, i.e. `total_with_vat = price_with_vat * quantity`).
   */
  total_with_vat?: number;
};
