// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Product
 *
 * Product details associated with a transaction.
 */
export type Product = {
  /**
   * Product name.
   */
  name?: string;
  /**
   * Human-readable label for the product price.
   */
  price_label?: string;
  /**
   * Product price.
   */
  price?: number;
  /**
   * VAT rate applied to the product price.
   */
  vat_rate?: number;
  /**
   * VAT amount for a single product.
   */
  single_vat_amount?: number;
  /**
   * Product price including VAT.
   */
  price_with_vat?: number;
  /**
   * Total VAT amount for the product quantity.
   */
  vat_amount?: number;
  /**
   * Product quantity.
   */
  quantity?: number;
  /**
   * Total price calculated as the product price multiplied by the quantity.
   */
  total_price?: number;
  /**
   * Total product price including VAT.
   */
  total_with_vat?: number;
};
