// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { ReaderPaymentResponseData } from "./reader-payment-response-data";

export type ReaderPaymentResponse = { data?: ReaderPaymentResponseData };
