// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Unique identifier of the object.
 *
 * Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.
 */
export type ReaderID = string;
