// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Metadata } from "./metadata";
import type { ReaderDevice } from "./reader-device";
import type { ReaderID } from "./reader-id";
import type { ReaderName } from "./reader-name";
import type { ReaderStatus } from "./reader-status";

/**
 * Reader
 *
 * A physical card reader device that can accept in-person payments.
 */
export type Reader = {
  id: ReaderID;
  name: ReaderName;
  status: ReaderStatus;
  device: ReaderDevice;
  metadata?: Metadata;
  /**
   * Identifier of the system-managed service account associated with this reader.
   * Present only for readers that are already paired.
   * This field is currently in beta and may change.
   */
  service_account_id?: string;
  /**
   * The timestamp of when the reader was created.
   */
  created_at: string;
  /**
   * The timestamp of when the reader was last updated.
   */
  updated_at: string;
};
