// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Information about the underlying physical device.
 */
export type ReaderDevice = {
  /**
   * A unique identifier of the physical device (e.g. serial number).
   */
  identifier: string;
  /**
   * Identifier of the model of the device.
   */
  model: "solo" | "virtual-solo";
};
