// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Affiliate } from "./affiliate";
import type { Amount } from "./amount";

export type ReaderPaymentRequestParams = {
  affiliate?: Affiliate;
  /**
   * Caller-supplied correlation identifier, used as the idempotency key.
   */
  client_transaction_id: string;
  /**
   * Optional tip amount in minor units, added on top of total_amount.
   */
  tip_amount?: number;
  total_amount: Amount;
};
