// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type ReaderPaymentResponseData = {
  /**
   * Caller-supplied correlation identifier that was provided in the request.
   */
  client_transaction_id?: string;
  /**
   * Transaction code returned by the acquirer/processing entity after processing the transaction.
   */
  transaction_code?: string;
};
