// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * ReaderCheckoutStatusChange
 *
 * The callback payload containing the status change of the Reader Checkout.
 */
export type ReaderCheckoutStatusChange = {
  /**
   * Type of event.
   */
  event_type: string;
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event payload.
   */
  payload: {
    /**
     * The unique client transaction id. It is the same returned by the Checkout.
     */
    client_transaction_id: string;
    /**
     * The merchant code associated with the transaction.
     */
    merchant_code: string;
    /**
     * The current status of the transaction.
     */
    status: "successful" | "failed";
    /**
     * The transaction id. Deprecated: use `client_transaction_id` instead.
     *
     * @deprecated
     */
    transaction_id?: string;
  };
  /**
   * Timestamp of the event.
   */
  timestamp: string;
};
