// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Receipt Card
 *
 * Payment card details displayed on the receipt.
 */
export type ReceiptCard = {
  /**
   * Card last 4 digits.
   */
  last_4_digits?: string;
  /**
   * Card Scheme.
   */
  type?: string;
};
