// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { ReceiptCard } from "./receipt-card";
import type { ReceiptEvent } from "./receipt-event";
import type { ReceiptReader } from "./receipt-reader";
import type { TransactionID } from "./transaction-id";

/**
 * Receipt Transaction
 *
 * Transaction details displayed on a receipt.
 */
export type ReceiptTransaction = {
  /**
   * Transaction code returned after processing the transaction.
   */
  transaction_code?: string;
  transaction_id?: TransactionID;
  /**
   * Short unique identifier for the merchant.
   */
  merchant_code?: string;
  /**
   * Total transaction amount, in major units.
   */
  amount?: string;
  /**
   * VAT included in the transaction amount, in major units.
   */
  vat_amount?: string;
  /**
   * Tip included in the transaction amount, in major units.
   */
  tip_amount?: string;
  /**
   * Three-letter ISO 4217 currency code of the transaction.
   */
  currency?: string;
  /**
   * The timestamp of when the transaction was created.
   */
  timestamp?: string;
  /**
   * Current processing status of the transaction.
   */
  status?: string;
  /**
   * Payment type used for the transaction.
   */
  payment_type?: string;
  /**
   * Entry mode of the payment details.
   */
  entry_mode?: string;
  /**
   * Cardholder verification method.
   */
  verification_method?: string;
  card_reader?: ReceiptReader;
  card?: ReceiptCard;
  /**
   * Number of installments.
   */
  installments_count?: number;
  /**
   * Whether the transaction was processed as credit or debit.
   */
  process_as?: "CREDIT" | "DEBIT";
  /**
   * Products associated with the transaction.
   */
  products?: {
    /**
     * Product name.
     */
    name?: string;
    /**
     * Product description.
     */
    description?: string;
    /**
     * Product price.
     */
    price?: string;
    /**
     * VAT rate.
     */
    vat_rate?: string;
    /**
     * VAT amount for a single product.
     */
    single_vat_amount?: string;
    /**
     * Product price including VAT.
     */
    price_with_vat?: string;
    /**
     * Total VAT amount for the product quantity.
     */
    vat_amount?: string;
    /**
     * Product quantity.
     */
    quantity?: number;
    /**
     * Total price calculated as the product price multiplied by the quantity.
     */
    total_price?: string;
    /**
     * Total product price including VAT.
     */
    total_with_vat?: string;
  }[];
  /**
   * VAT breakdown for the transaction.
   */
  vat_rates?: {
    /**
     * Gross amount to which the VAT rate applies.
     */
    gross?: number;
    /**
     * Net amount to which the VAT rate applies.
     */
    net?: number;
    /**
     * VAT rate applied to the transaction amount.
     */
    rate?: number;
    /**
     * VAT amount included in the gross amount.
     */
    vat?: number;
  }[];
  /**
   * Transaction events displayed on the receipt.
   */
  events?: ReceiptEvent[];
  /**
   * Receipt number associated with the transaction.
   */
  receipt_no?: string;
};
