// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { TransactionEventID } from "./transaction-event-id";
import type { TransactionEventStatus } from "./transaction-event-status";
import type { TransactionEventType } from "./transaction-event-type";
import type { TransactionID } from "./transaction-id";

/**
 * Receipt Event
 *
 * Transaction event details as rendered on the receipt.
 */
export type ReceiptEvent = {
  id?: TransactionEventID;
  transaction_id?: TransactionID;
  type?: TransactionEventType;
  status?: TransactionEventStatus;
  /**
   * Amount of the event.
   */
  amount?: string;
  /**
   * Date and time of the transaction event.
   */
  timestamp?: string;
  /**
   * Receipt number associated with the event.
   */
  receipt_no?: string;
};
