// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { ReceiptMerchantData } from "./receipt-merchant-data";
import type { ReceiptTransaction } from "./receipt-transaction";

/**
 * Receipt
 *
 * Structured receipt details for a transaction. The transaction's `amount`, `vat_amount`, and `tip_amount`, as well as event amounts, are returned as decimal strings in major currency units, for example `"10.10"` for EUR 10.10.
 */
export type Receipt = {
  transaction_data?: ReceiptTransaction;
  merchant_data?: ReceiptMerchantData;
  /**
   * EMV-specific metadata returned for card-present payments.
   */
  emv_data?: Record<string, unknown>;
  /**
   * Acquirer-specific metadata related to the card authorization.
   */
  acquirer_data?: {
    /**
     * Identifier of the terminal used for the authorization.
     */
    tid?: string;
    /**
     * Authorization code returned by the acquirer.
     */
    authorization_code?: string;
    /**
     * Return code reported by the acquirer.
     */
    return_code?: string;
    /**
     * Local timestamp of the card authorization.
     */
    local_time?: string;
  };
};
