// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type ReceiptCard = {
  /**
   * Card last 4 digits.
   */
  last_4_digits?: string;
  /**
   * Card Scheme.
   */
  type?: string;
};
