// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Receipt Reader
 *
 * Card reader details displayed on the receipt.
 */
export type ReceiptReader = {
  /**
   * Reader serial number.
   */
  code?: string;
  /**
   * Reader type.
   */
  type?: string;
};
