// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Receipt Merchant Data
 *
 * Receipt merchant data
 */
export type ReceiptMerchantData = {
  /**
   * Merchant profile details displayed on the receipt.
   */
  merchant_profile?: {
    merchant_code?: string;
    business_name?: string;
    email?: string;
    address?: {
      address_line1?: string;
      city?: string;
      country?: string;
      country_en_name?: string;
      country_native_name?: string;
      post_code?: string;
      landline?: string;
    };
  };
  /**
   * Locale used for rendering localized receipt fields.
   */
  locale?: string;
};
