// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Receipt Card
 *
 * Payment card details displayed on the receipt.
 */
export type ReceiptCard = {
  /**
   * Last four digits of the payment card number.
   */
  last_4_digits?: string;
  /**
   * Issuing card network of the payment card.
   */
  type?: string;
};
