// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { EventID } from "./event-id";
import type { EventStatus } from "./event-status";
import type { EventType } from "./event-type";
import type { TransactionID } from "./transaction-id";

export type ReceiptEvent = {
  id?: EventID;
  transaction_id?: TransactionID;
  type?: EventType;
  status?: EventStatus;
  /**
   * Amount of the event.
   */
  amount?: string;
  /**
   * Date and time of the transaction event.
   */
  timestamp?: string;
  receipt_no?: string;
};
