// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { ReceiptCard } from "./receipt-card";
import type { ReceiptEvent } from "./receipt-event";
import type { ReceiptReader } from "./receipt-reader";
import type { TransactionID } from "./transaction-id";

/**
 * Receipt Transaction
 *
 * Transaction information.
 */
export type ReceiptTransaction = {
  /**
   * Transaction code.
   */
  transaction_code?: string;
  transaction_id?: TransactionID;
  /**
   * Merchant code.
   */
  merchant_code?: string;
  /**
   * Transaction amount.
   */
  amount?: string;
  /**
   * Transaction VAT amount.
   */
  vat_amount?: string;
  /**
   * Tip amount (included in transaction amount).
   */
  tip_amount?: string;
  /**
   * Transaction currency.
   */
  currency?: string;
  /**
   * Time created at.
   */
  timestamp?: string;
  /**
   * Transaction processing status.
   */
  status?: string;
  /**
   * Transaction type.
   */
  payment_type?: string;
  /**
   * Transaction entry mode.
   */
  entry_mode?: string;
  /**
   * Cardholder verification method.
   */
  verification_method?: string;
  card_reader?: ReceiptReader;
  card?: ReceiptCard;
  /**
   * Number of installments.
   */
  installments_count?: number;
  /**
   * Debit/Credit.
   */
  process_as?: "CREDIT" | "DEBIT";
  /**
   * Products
   */
  products?: {
    /**
     * Product name
     */
    name?: string;
    /**
     * Product description
     */
    description?: string;
    /**
     * Product price
     */
    price?: string;
    /**
     * VAT rate
     */
    vat_rate?: string;
    /**
     * VAT amount for a single product
     */
    single_vat_amount?: string;
    /**
     * Product price including VAT
     */
    price_with_vat?: string;
    /**
     * VAT amount
     */
    vat_amount?: string;
    /**
     * Product quantity
     */
    quantity?: number;
    /**
     * Quantity x product price
     */
    total_price?: string;
    /**
     * Total price including VAT
     */
    total_with_vat?: string;
  }[];
  /**
   * Vat rates.
   */
  vat_rates?: {
    /**
     * Gross
     */
    gross?: number;
    /**
     * Net
     */
    net?: number;
    /**
     * Rate
     */
    rate?: number;
    /**
     * Vat
     */
    vat?: number;
  }[];
  /**
   * Events
   */
  events?: ReceiptEvent[];
  /**
   * Receipt number
   */
  receipt_no?: string;
};
