// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * The type of the membership resource.
 * Possible values are:
 * * `merchant` - merchant account(s)
 * * `organization` - organization(s)
 */
export type ResourceType = string;
