// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Metadata } from "./metadata";

/**
 * Role
 *
 * A custom role that can be used to assign set of permissions to members.
 */
export type Role = {
  /**
   * Unique identifier of the role.
   */
  id: string;
  /**
   * User-defined name of the role.
   */
  name: string;
  /**
   * User-defined description of the role.
   */
  description?: string;
  /**
   * List of permission granted by this role.
   */
  permissions: string[];
  /**
   * True if the role is provided by SumUp.
   */
  is_predefined: boolean;
  metadata?: Metadata;
  /**
   * The timestamp of when the role was created.
   */
  created_at: string;
  /**
   * The timestamp of when the role was last updated.
   */
  updated_at: string;
};
