// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * StatusResponse
 *
 * Status of a device
 */
export type StatusResponse = {
  data: {
    /**
     * Battery level percentage
     */
    battery_level?: number;
    /**
     * Battery temperature in Celsius
     */
    battery_temperature?: number;
    /**
     * Type of connection used by the device
     */
    connection_type?:
      | "btle"
      | "edge"
      | "gprs"
      | "lte"
      | "umts"
      | "usb"
      | "Wi-Fi";
    /**
     * Firmware version of the device
     */
    firmware_version?: string;
    /**
     * Timestamp of the last activity from the device
     */
    last_activity?: string;
    /**
     * Latest state of the device
     */
    state?:
      | "IDLE"
      | "SELECTING_TIP"
      | "WAITING_FOR_CARD"
      | "WAITING_FOR_PIN"
      | "WAITING_FOR_SIGNATURE"
      | "UPDATING_FIRMWARE";
    /**
     * Status of a device
     */
    status: "ONLINE" | "OFFLINE";
  };
};
