// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Time Offset Details
 *
 * TimeOffset Details
 */
export type TimeoffsetDetails = {
  /**
   * Postal code
   */
  post_code?: string;
  /**
   * UTC offset
   */
  offset?: number;
  /**
   * Daylight Saving Time
   */
  dst?: boolean;
};
