// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Currency } from "./currency";
import type { PaymentType } from "./payment-type";
import type { TransactionStatus } from "./transaction-status";

/**
 * Transaction Base
 *
 * Core details shared by transaction resources.
 */
export type TransactionBase = {
  /**
   * Unique identifier of the transaction.
   */
  id?: string;
  /**
   * SumUp transaction code, for example `TEENSK4W2K`. Use it to look up the transaction with the `transaction_code` query parameter. This is separate from the transaction's `id` and the card issuer's `auth_code`.
   */
  transaction_code?: string;
  /**
   * Total amount of the transaction in major units of `currency`, for example `10.1` for EUR 10.10.
   */
  amount?: number;
  currency?: Currency;
  /**
   * The timestamp of when the transaction was created.
   */
  timestamp?: string;
  status?: TransactionStatus;
  payment_type?: PaymentType;
  /**
   * Number of installments for a deferred payment.
   */
  installments_count?: number;
};
