// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Transaction Event ID
 *
 * Numeric identifier of a transaction event. Use it as `tx_event_id` when requesting receipt details for a specific event. This is separate from the transaction ID and the transaction history pagination references.
 */
export type TransactionEventID = number;
