// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { TransactionEventID } from "./transaction-event-id";
import type { TransactionEventStatus } from "./transaction-event-status";
import type { TransactionEventType } from "./transaction-event-type";

/**
 * Transaction Event
 *
 * Detailed information about a transaction event.
 */
export type TransactionEvent = {
  id?: TransactionEventID;
  event_type?: TransactionEventType;
  status?: TransactionEventStatus;
  /**
   * Amount of the event.
   */
  amount?: number;
  /**
   * Date when the transaction event is due to occur.
   */
  due_date?: string;
  /**
   * Date when the transaction event occurred.
   */
  date?: string;
  /**
   * Consecutive number of the installment that is paid. Applicable only payout events, i.e. `event_type = PAYOUT`.
   */
  installment_number?: number;
  /**
   * Date and time of the transaction event.
   */
  timestamp?: string;
};
