// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CardType } from "./card-type";
import type { TransactionBase } from "./transaction-base";
import type { TransactionID } from "./transaction-id";
import type { TransactionMixinHistory } from "./transaction-mixin-history";

export type TransactionHistory = TransactionBase &
  TransactionMixinHistory & {
    transaction_id?: TransactionID;
    /**
     * Client-specific ID of the transaction.
     */
    client_transaction_id?: string;
    /**
     * Email address of the registered user (merchant) to whom the payment is made.
     */
    user?: string;
    /**
     * Type of the transaction for the registered user specified in the `user` property.
     */
    type?: "PAYMENT" | "REFUND" | "CHARGE_BACK";
    card_type?: CardType;
  };
