// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { Currency } from "./currency";
import type { PaymentType } from "./payment-type";
import type { TransactionStatus } from "./transaction-status";

/**
 * Transaction Base
 *
 * Core details shared by transaction resources.
 */
export type TransactionBase = {
  /**
   * Unique identifier of the transaction.
   */
  id?: string;
  /**
   * Transaction code returned by the acquirer/processing entity after processing the transaction.
   */
  transaction_code?: string;
  /**
   * Total amount of the transaction.
   */
  amount?: number;
  currency?: Currency;
  /**
   * The timestamp of when the transaction was created.
   */
  timestamp?: string;
  status?: TransactionStatus;
  payment_type?: PaymentType;
  /**
   * Number of installments for a deferred payment.
   */
  installments_count?: number;
};
