// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { EventID } from "./event-id";
import type { EventStatus } from "./event-status";
import type { EventType } from "./event-type";

/**
 * Details of a transaction event.
 */
export type TransactionEvent = {
  id?: EventID;
  event_type?: EventType;
  status?: EventStatus;
  /**
   * Amount of the event.
   */
  amount?: number;
  /**
   * Date when the transaction event is due to occur.
   */
  due_date?: string;
  /**
   * Date when the transaction event occurred.
   */
  date?: string;
  /**
   * Consecutive number of the installment that is paid. Applicable only payout events, i.e. `event_type = PAYOUT`.
   */
  installment_number?: number;
  /**
   * Date and time of the transaction event.
   */
  timestamp?: string;
};
