// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Transaction Event Type
 *
 * Type of the transaction event.
 */
export type TransactionEventType =
  | "PAYOUT"
  | "CHARGE_BACK"
  | "REFUND"
  | "PAYOUT_DEDUCTION";
