// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Transaction Status
 *
 * Current status of the transaction.
 *
 * - `PENDING`: The transaction has been created but its final outcome is not known yet.
 * - `SUCCESSFUL`: The transaction completed successfully.
 * - `CANCELLED`: The transaction was cancelled or otherwise reversed before completion.
 * - `FAILED`: The transaction attempt did not complete successfully.
 * - `REFUNDED`: The transaction was refunded in full or in part.
 */
export type TransactionStatus =
  | "SUCCESSFUL"
  | "CANCELLED"
  | "FAILED"
  | "PENDING"
  | "REFUNDED";
