// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Transactions History Link
 *
 * Hypermedia link used for transaction history pagination.
 */
export type TransactionsHistoryLink = {
  /**
   * Pagination relation indicating which page the link retrieves, for example `next`.
   */
  rel: string;
  /**
   * Query string to use with the transaction history endpoint when requesting the linked page. Preserve the returned pagination references and query parameters.
   */
  href: string;
};
