// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { EntryMode } from "./entry-mode";

/**
 * Transaction Checkout Info
 *
 * Checkout-specific fields associated with a transaction.
 */
export type TransactionCheckoutInfo = {
  /**
   * Unique code of the registered merchant to whom the payment is made.
   */
  merchant_code?: string;
  /**
   * VAT included in the total transaction amount, in major units of the transaction's currency.
   */
  vat_amount?: number;
  /**
   * Tip included in the total transaction amount, in major units of the transaction's currency.
   */
  tip_amount?: number;
  entry_mode?: EntryMode;
  /**
   * Authorization code for the transaction sent by the payment card issuer or bank. Applicable only to card payments.
   */
  auth_code?: string;
};
