// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import type { CardResponse } from "./card-response";
import type { Event } from "./event";
import type { HorizontalAccuracy } from "./horizontal-accuracy";
import type { Lat } from "./lat";
import type { Lon } from "./lon";
import type { Product } from "./product";
import type { TransactionBase } from "./transaction-base";
import type { TransactionCheckoutInfo } from "./transaction-checkout-info";
import type { TransactionEvent } from "./transaction-event";
import type { TransactionMixinHistory } from "./transaction-mixin-history";

export type TransactionFull = TransactionBase &
  TransactionCheckoutInfo &
  TransactionMixinHistory & {
    /**
     * Email address of the registered user (merchant) to whom the payment is made.
     */
    username?: string;
    lat?: Lat;
    lon?: Lon;
    horizontal_accuracy?: HorizontalAccuracy;
    /**
     * Simple name of the payment type.
     */
    simple_payment_type?:
      | "MOTO"
      | "CASH"
      | "CC_SIGNATURE"
      | "ELV"
      | "CC_CUSTOMER_ENTERED"
      | "MANUAL_ENTRY"
      | "EMV";
    /**
     * Verification method used for the transaction.
     */
    verification_method?:
      | "none"
      | "na"
      | "signature"
      | "offline PIN"
      | "online PIN"
      | "offline PIN + signature"
      | "confirmation code verified";
    card?: CardResponse;
    /**
     * Local date and time of the creation of the transaction.
     */
    local_time?: string;
    /**
     * Payout type for the transaction.
     */
    payout_type?: "BANK_ACCOUNT" | "BALANCE" | "PREPAID_CARD";
    /**
     * List of products from the merchant's catalogue for which the transaction serves as a payment.
     */
    products?: Product[];
    /**
     * List of VAT rates applicable to the transaction.
     */
    vat_rates?: Record<string, unknown>[];
    /**
     * List of transaction events related to the transaction.
     */
    transaction_events?: TransactionEvent[];
    /**
     * Status generated from the processing status and the latest transaction state.
     */
    simple_status?:
      | "SUCCESSFUL"
      | "PAID_OUT"
      | "CANCEL_FAILED"
      | "CANCELLED"
      | "CHARGEBACK"
      | "FAILED"
      | "REFUND_FAILED"
      | "REFUNDED"
      | "NON_COLLECTION";
    /**
     * List of hyperlinks for accessing related resources.
     */
    links?: Record<string, unknown>[];
    /**
     * List of events related to the transaction.
     */
    events?: Event[];
    /**
     * Details of the payment location as received from the payment terminal.
     */
    location?: {
      lat?: Lat;
      lon?: Lon;
      horizontal_accuracy?: HorizontalAccuracy;
    };
    /**
     * Indicates whether tax deduction is enabled for the transaction.
     */
    tax_enabled?: boolean;
  };
