// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

export type TransactionMixinHistory = {
  /**
   * Short description of the payment. The value is taken from the `description` property of the related checkout resource.
   */
  product_summary?: string;
  /**
   * Total number of payouts to the registered user specified in the `user` property.
   */
  payouts_total?: number;
  /**
   * Number of payouts that are made to the registered user specified in the `user` property.
   */
  payouts_received?: number;
  /**
   * Payout plan of the registered user at the time when the transaction was made.
   */
  payout_plan?:
    | "SINGLE_PAYMENT"
    | "TRUE_INSTALLMENT"
    | "ACCELERATED_INSTALLMENT";
};
