// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Transactions History Link
 *
 * Hypermedia link used for transaction history pagination.
 */
export type TransactionsHistoryLink = {
  /**
   * Relation.
   */
  rel: string;
  /**
   * Location.
   */
  href: string;
};
