// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Unauthorized
 *
 * 401 Unauthorized
 */
export type Unauthorized = {
  errors: {
    /**
     * Fuller message giving context to error
     */
    detail?: string;
    /**
     * Key indicating type of error
     */
    type: "INVALID_ACCESS_TOKEN" | "INVALID_PASSWORD";
  };
};
