// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * Merchant VAT rates
 */
export type VatRates = {
  /**
   * Internal ID
   */
  id?: number;
  /**
   * Description
   */
  description?: string;
  /**
   * Rate
   */
  rate?: number;
  /**
   * Ordering
   */
  ordering?: number;
  /**
   * Country ISO code
   */
  country?: string;
};
