// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

/**
 * The version of the resource. The version reflects a specific change submitted to the API via one of the `PATCH` endpoints.
 *
 */
export type Version = string;
