// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import { type APIPromise, APIResource, type RequestOptions } from "../../core";
import type {
  Customer,
  ErrorBody,
  ErrorExtended,
  ErrorForbidden,
  PaymentInstrumentResponse,
  PersonalDetails,
  Problem,
} from "../../types";
export type CreateCustomerError =
  | ErrorExtended
  | { instance?: string; error_code?: string; error_message?: string };

export type UpdateCustomerParams = { personal_details?: PersonalDetails };

export type ListPaymentInstrumentsResponse = PaymentInstrumentResponse[];

export class Customers extends APIResource {
  /**
   * Creates a new saved customer resource which you can later manipulate and save payment instruments to.
   */
  create(
    body: Customer,
    options?: RequestOptions,
  ): APIPromise<
    Customer,
    CreateCustomerError | Problem | ErrorForbidden | ErrorBody
  > {
    return this._client.post<
      Customer,
      CreateCustomerError | Problem | ErrorForbidden | ErrorBody
    >({
      path: `/v0.1/customers`,
      body,
      ...options,
    });
  }

  /**
   * Retrieves an identified saved customer resource through the unique `customer_id` parameter, generated upon customer creation.
   */
  get(
    customerId: string,
    options?: RequestOptions,
  ): APIPromise<Customer, Problem | ErrorForbidden | ErrorBody> {
    return this._client.get<Customer, Problem | ErrorForbidden | ErrorBody>({
      path: `/v0.1/customers/${customerId}`,
      ...options,
    });
  }

  /**
   * Updates an identified saved customer resource's personal details.
   *
   * The request only overwrites the parameters included in the request, all other parameters will remain with their initially assigned values.
   *
   */
  update(
    customerId: string,
    body: UpdateCustomerParams,
    options?: RequestOptions,
  ): APIPromise<Customer, Problem | ErrorForbidden | ErrorBody> {
    return this._client.put<Customer, Problem | ErrorForbidden | ErrorBody>({
      path: `/v0.1/customers/${customerId}`,
      body,
      ...options,
    });
  }

  /**
   * Lists all payment instrument resources that are saved for an identified customer.
   */
  listPaymentInstruments(
    customerId: string,
    options?: RequestOptions,
  ): APIPromise<
    PaymentInstrumentResponse[],
    Problem | ErrorForbidden | ErrorBody
  > {
    return this._client.get<
      PaymentInstrumentResponse[],
      Problem | ErrorForbidden | ErrorBody
    >({
      path: `/v0.1/customers/${customerId}/payment-instruments`,
      ...options,
    });
  }

  /**
   * Deactivates an identified card payment instrument resource for a customer.
   */
  deactivatePaymentInstrument(
    customerId: string,
    token: string,
    options?: RequestOptions,
  ): APIPromise<void, ErrorBody | Problem | ErrorForbidden> {
    return this._client.delete<void, ErrorBody | Problem | ErrorForbidden>({
      path: `/v0.1/customers/${customerId}/payment-instruments/${token}`,
      ...options,
    });
  }
}
