// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import {
  APIResource,
  type RequestOptions,
  type WithResponse,
} from "../../core";
import type {
  Customer,
  ErrorExtended,
  PaymentInstrumentResponse,
  PersonalDetails,
} from "../../types";
export type CreateCustomerError =
  | ErrorExtended
  | {
      /**
       * Unique identifier of this error occurrence.
       */
      instance: string;
      /**
       * Platform code for the error.
       */
      error_code: string;
      /**
       * Short description of the error.
       */
      error_message: string;
    };

export type UpdateCustomerParams = { personal_details?: PersonalDetails };

export type ListPaymentInstrumentsResponse = PaymentInstrumentResponse[];

/**
 * API resource for the Customers endpoints.
 *
 * Customers represent payers in your integration. Create a customer with your own `customer_id` to associate their personal details and saved payment instruments with your business records.
 *
 * To save a card, create a checkout for that customer with `purpose = SETUP_RECURRING_PAYMENT`, then process it with the payer's consent and mandate details. See the [tokenization guide](https://developer.sumup.com/online-payments/guides/tokenization-with-payment-sdk/).
 *
 * Use the Customers endpoints to create, retrieve, or update customer details and to list or deactivate saved payment instruments. For subsequent payments, process a new checkout with the saved instrument's `token` and its associated `customer_id`.
 */
export class Customers extends APIResource {
  /**
   * Creates a customer using the `customer_id` you supply. Choose an identifier that maps to the payer in your own system and reuse it when retrieving the customer or associating checkouts and saved payment instruments with them.
   */
  create(body: Customer, options?: RequestOptions): Promise<Customer> {
    return this._client.post<Customer>({
      path: `/v0.1/customers`,
      body,
      ...options,
    });
  }

  createWithResponse(
    body: Customer,
    options?: RequestOptions,
  ): Promise<WithResponse<Customer>> {
    return this._client.postWithResponse<Customer>({
      path: `/v0.1/customers`,
      body,
      ...options,
    });
  }

  /**
   * Retrieves a saved customer using the `customer_id` you supplied when creating the customer.
   */
  get(customerId: string, options?: RequestOptions): Promise<Customer> {
    return this._client.get<Customer>({
      path: `/v0.1/customers/${customerId}`,
      ...options,
    });
  }

  getWithResponse(
    customerId: string,
    options?: RequestOptions,
  ): Promise<WithResponse<Customer>> {
    return this._client.getWithResponse<Customer>({
      path: `/v0.1/customers/${customerId}`,
      ...options,
    });
  }

  /**
   * Updates an identified saved customer resource's personal details.
   *
   * The request only overwrites the parameters included in the request, all other parameters will remain with their initially assigned values.
   */
  update(
    customerId: string,
    body: UpdateCustomerParams,
    options?: RequestOptions,
  ): Promise<Customer> {
    return this._client.put<Customer>({
      path: `/v0.1/customers/${customerId}`,
      body,
      ...options,
    });
  }

  updateWithResponse(
    customerId: string,
    body: UpdateCustomerParams,
    options?: RequestOptions,
  ): Promise<WithResponse<Customer>> {
    return this._client.putWithResponse<Customer>({
      path: `/v0.1/customers/${customerId}`,
      body,
      ...options,
    });
  }

  /**
   * Lists all payment instrument resources that are saved for an identified customer.
   */
  listPaymentInstruments(
    customerId: string,
    options?: RequestOptions,
  ): Promise<PaymentInstrumentResponse[]> {
    return this._client.get<PaymentInstrumentResponse[]>({
      path: `/v0.1/customers/${customerId}/payment-instruments`,
      ...options,
    });
  }

  listPaymentInstrumentsWithResponse(
    customerId: string,
    options?: RequestOptions,
  ): Promise<WithResponse<PaymentInstrumentResponse[]>> {
    return this._client.getWithResponse<PaymentInstrumentResponse[]>({
      path: `/v0.1/customers/${customerId}/payment-instruments`,
      ...options,
    });
  }

  /**
   * Deactivates an identified card payment instrument resource for a customer.
   */
  deactivatePaymentInstrument(
    customerId: string,
    token: string,
    options?: RequestOptions,
  ): Promise<void> {
    return this._client.delete<void>({
      path: `/v0.1/customers/${customerId}/payment-instruments/${token}`,
      ...options,
    });
  }

  deactivatePaymentInstrumentWithResponse(
    customerId: string,
    token: string,
    options?: RequestOptions,
  ): Promise<WithResponse<void>> {
    return this._client.deleteWithResponse<void>({
      path: `/v0.1/customers/${customerId}/payment-instruments/${token}`,
      ...options,
    });
  }
}
