// Code generated by @sumup/ts-sdk-gen@0.0.1. DO NOT EDIT.

import * as Core from "../../core";

/**
 * Amount of the event.
 */
export type AmountEvent = number;

/**
 * Unique ID of the transaction event.
 */
export type EventID = number;

/**
 * Status of the transaction event.
 */
export type EventStatus =
  | "PENDING"
  | "SCHEDULED"
  | "FAILED"
  | "REFUNDED"
  | "SUCCESSFUL"
  | "PAID_OUT";

/**
 * Date and time of the transaction event.
 */
export type TimestampEvent = string;

/**
 * Unique ID of the transaction.
 */
export type TransactionID = string;

/**
 * Type of the transaction event.
 */
export type EventType =
  | "PAYOUT"
  | "CHARGE_BACK"
  | "REFUND"
  | "PAYOUT_DEDUCTION";

/**
 * Receipt merchant data
 */
export type ReceiptMerchantData = {
  locale?: string;
  merchant_profile?: {
    address?: {
      address_line1?: string;
      city?: string;
      country?: string;
      country_en_name?: string;
      country_native_name?: string;
      landline?: string;
      post_code?: string;
    };
    business_name?: string;
    email?: string;
    merchant_code?: string;
  };
};

export type ReceiptCard = {
  /**
   * Card last 4 digits.
   */
  last_4_digits?: string;
  /**
   * Card Scheme.
   */
  type?: string;
};

export type ReceiptEvent = {
  amount?: AmountEvent;
  id?: EventID;
  receipt_no?: string;
  status?: EventStatus;
  timestamp?: TimestampEvent;
  transaction_id?: TransactionID;
  type?: EventType;
};

/**
 * Transaction information.
 */
export type ReceiptTransaction = {
  /**
   * Transaction amount.
   */
  amount?: string;
  card?: ReceiptCard;
  /**
   * Transaction currency.
   */
  currency?: string;
  /**
   * Transaction entry mode.
   */
  entry_mode?: string;
  /**
   * Events
   */
  events?: ReceiptEvent[];
  /**
   * Number of installments.
   */
  installments_count?: number;
  /**
   * Transaction type.
   */
  payment_type?: string;
  /**
   * Products
   */
  products?: {
    /**
     * Product description.
     */
    description?: string;
    /**
     * Product name.
     */
    name?: string;
    /**
     * Product price.
     */
    price?: number;
    /**
     * Product quantity.
     */
    quantity?: number;
    /**
     * Quantity x product price.
     */
    total_price?: number;
  }[];
  /**
   * Receipt number
   */
  receipt_no?: string;
  /**
   * Transaction processing status.
   */
  status?: string;
  /**
   * Time created at.
   */
  timestamp?: string;
  /**
   * Tip amount (included in transaction amount).
   */
  tip_amount?: string;
  /**
   * Transaction code.
   */
  transaction_code?: string;
  /**
   * Transaction VAT amount.
   */
  vat_amount?: string;
  /**
   * Vat rates.
   */
  vat_rates?: {
    /**
     * Gross
     */
    gross?: number;
    /**
     * Net
     */
    net?: number;
    /**
     * Rate
     */
    rate?: number;
    /**
     * Vat
     */
    vat?: number;
  }[];
  /**
   * Cardholder verification method.
   */
  verification_method?: string;
};

/**
 * Receipt
 */
export type Receipt = {
  acquirer_data?: {
    authorization_code?: string;
    local_time?: string;
    return_code?: string;
    tid?: string;
  };
  emv_data?: Record<string, unknown>;
  merchant_data?: ReceiptMerchantData;
  transaction_data?: ReceiptTransaction;
};

export type GetReceiptQueryParams = {
  mid: string;
  txEventId?: number;
};

export class Receipts extends Core.APIResource {
  /**
   * Retrieve receipt details
   */
  get(
    id: string,
    query: GetReceiptQueryParams,
    params?: Core.FetchParams,
  ): Core.APIPromise<Receipt> {
    return this._client.get<Receipt>({
      path: `/v1.1/receipts/${id}`,
      query,
      ...params,
    });
  }
}

export declare namespace Receipts {
  export type {
    AmountEvent,
    EventID,
    EventStatus,
    EventType,
    GetReceiptQueryParams,
    Receipt,
    ReceiptCard,
    ReceiptEvent,
    ReceiptMerchantData,
    ReceiptTransaction,
    TimestampEvent,
    TransactionID,
  };
}
