// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import { type APIPromise, APIResource, type RequestOptions } from "../../core";
import type { ErrorExtended, FinancialPayouts, Problem } from "../../types";
export type ListPayoutsV1QueryParams = {
  start_date: string;
  end_date: string;
  format?: "json" | "csv";
  limit?: number;
  order?: "desc" | "asc";
};

export type ListPayoutsV1Error = ErrorExtended[];

export type ListPayoutsQueryParams = {
  start_date: string;
  end_date: string;
  format?: "json" | "csv";
  limit?: number;
  order?: "desc" | "asc";
};

export type ListPayoutsError = ErrorExtended[];

export class Payouts extends APIResource {
  /**
   * Lists ordered payouts for the merchant profile.
   */
  list(
    merchantCode: string,
    query: ListPayoutsV1QueryParams,
    options?: RequestOptions,
  ): APIPromise<FinancialPayouts, ErrorExtended[] | Problem> {
    return this._client.get<FinancialPayouts, ErrorExtended[] | Problem>({
      path: `/v1.0/merchants/${merchantCode}/payouts`,
      query,
      ...options,
    });
  }

  /**
   * Lists ordered payouts for the merchant profile.
   */
  listDeprecated(
    query: ListPayoutsQueryParams,
    options?: RequestOptions,
  ): APIPromise<FinancialPayouts, ErrorExtended[] | Problem> {
    return this._client.get<FinancialPayouts, ErrorExtended[] | Problem>({
      path: `/v0.1/me/financials/payouts`,
      query,
      ...options,
    });
  }
}
