// Code generated by @sumup/ts-sdk-gen@0.0.1. DO NOT EDIT.

import * as Core from "../../core";

export type OAuth2Scopes = (
  | "accounting.read"
  | "accounting.write"
  | "email"
  | "invoices.read"
  | "invoices.write"
  | "payment_instruments"
  | "payments"
  | "products"
  | "profile"
  | "readers.read"
  | "readers.write"
  | "transactions.history"
  | "user.app-settings"
  | "user.payout-settings"
  | "user.profile"
  | "user.profile_readonly"
  | "user.subaccounts"
)[];

/**
 * API Key
 */
export type APIKey = {
  created_at: string;
  /**
   * Unique identifier of the API Key.
   *
   */
  id: string;
  /**
   * User-assigned name of the API Key.
   */
  name: string;
  /**
   * The plaintext value of the API key. This field is returned only in the response to API key creation and is never again available in the plaintext form.
   *
   */
  plaintext?: string;
  /**
   * Last 8 characters of the API key.
   *
   */
  preview: string;
  scopes: OAuth2Scopes;
  type: "public" | "secret";
  updated_at: string;
};

export type APIKeysList = { items: APIKey[]; total_count: number };

export type ListApiKeysQueryParams = {
  offset?: number;
  limit?: number;
};

export type CreateApiKeyParams = { name: string; scopes: OAuth2Scopes };

export type UpdateApiKeyParams = {
  /**
   * New name for the API key.
   */
  name: string;
  scopes: OAuth2Scopes;
};

export class ApiKeys extends Core.APIResource {
  /**
   * List API keys
   */
  listApiKeys(
    merchantCode: string,
    query?: ListApiKeysQueryParams,
    params?: Core.FetchParams,
  ): Core.APIPromise<APIKeysList> {
    return this._client.get<APIKeysList>({
      path: `/v0.1/merchants/${merchantCode}/api-keys`,
      query,
      ...params,
    });
  }

  /**
   * Create an API key
   */
  createApiKey(
    merchantCode: string,
    body: CreateApiKeyParams,
    params?: Core.FetchParams,
  ): Core.APIPromise<APIKey> {
    return this._client.post<APIKey>({
      path: `/v0.1/merchants/${merchantCode}/api-keys`,
      body,
      ...params,
    });
  }

  /**
   * Retrieve an API Key
   */
  getApiKey(
    merchantCode: string,
    keyId: string,
    params?: Core.FetchParams,
  ): Core.APIPromise<APIKey> {
    return this._client.get<APIKey>({
      path: `/v0.1/merchants/${merchantCode}/api-keys/${keyId}`,
      ...params,
    });
  }

  /**
   * Update an API key
   */
  updateApiKey(
    merchantCode: string,
    keyId: string,
    body: UpdateApiKeyParams,
    params?: Core.FetchParams,
  ): Core.APIPromise<void> {
    return this._client.put<void>({
      path: `/v0.1/merchants/${merchantCode}/api-keys/${keyId}`,
      body,
      ...params,
    });
  }

  /**
   * Revoke an API key
   */
  revokeApiKey(
    merchantCode: string,
    keyId: string,
    params?: Core.FetchParams,
  ): Core.APIPromise<void> {
    return this._client.delete<void>({
      path: `/v0.1/merchants/${merchantCode}/api-keys/${keyId}`,
      ...params,
    });
  }
}

export declare namespace ApiKeys {
  export type {
    APIKey,
    APIKeysList,
    CreateApiKeyParams,
    ListApiKeysQueryParams,
    OAuth2Scopes,
    UpdateApiKeyParams,
  };
}
