// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import {
  APIResource,
  type RequestOptions,
  splitOptionalQueryAndOptions,
  type WithResponse,
} from "../../core";
import type { Operator, Problem } from "../../types";
export type ListSubAccountsQueryParams = {
  query?: string;
  include_primary?: boolean;
};

export type ListSubAccountsResponse = Operator[];

export type CreateSubAccountParams = {
  username: string;
  password: string;
  nickname?: string;
  permissions?: {
    create_moto_payments?: boolean;
    create_referral?: boolean;
    full_transaction_history_view?: boolean;
    refund_transactions?: boolean;
  };
};

export type UpdateSubAccountParams = {
  password?: string;
  username?: string;
  disabled?: boolean;
  nickname?: string;
  permissions?: {
    create_moto_payments?: boolean;
    create_referral?: boolean;
    full_transaction_history_view?: boolean;
    refund_transactions?: boolean;
  };
};

/**
 * API resource for the Subaccounts endpoints.
 *
 * Endpoints for managing merchant sub-accounts (operators).
 */
export class Subaccounts extends APIResource {
  /**
   * Returns list of operators for currently authorized user's merchant.
   */
  listSubAccounts(
    query?: ListSubAccountsQueryParams,
    options?: RequestOptions,
  ): Promise<Operator[]>;
  listSubAccounts(options?: RequestOptions): Promise<Operator[]>;
  listSubAccounts(
    queryOrOptions?: ListSubAccountsQueryParams | RequestOptions,
    options?: RequestOptions,
  ): Promise<Operator[]> {
    const { query, options: requestOptions } =
      splitOptionalQueryAndOptions<ListSubAccountsQueryParams>(
        queryOrOptions,
        options,
      );
    return this._client.get<Operator[]>({
      path: `/v0.1/me/accounts`,
      query,
      ...requestOptions,
    });
  }

  listSubAccountsWithResponse(
    query?: ListSubAccountsQueryParams,
    options?: RequestOptions,
  ): Promise<WithResponse<Operator[]>>;
  listSubAccountsWithResponse(
    options?: RequestOptions,
  ): Promise<WithResponse<Operator[]>>;
  listSubAccountsWithResponse(
    queryOrOptions?: ListSubAccountsQueryParams | RequestOptions,
    options?: RequestOptions,
  ): Promise<WithResponse<Operator[]>> {
    const { query, options: requestOptions } =
      splitOptionalQueryAndOptions<ListSubAccountsQueryParams>(
        queryOrOptions,
        options,
      );
    return this._client.getWithResponse<Operator[]>({
      path: `/v0.1/me/accounts`,
      query,
      ...requestOptions,
    });
  }

  /**
   * Creates new operator for currently authorized users' merchant.
   */
  createSubAccount(
    body: CreateSubAccountParams,
    options?: RequestOptions,
  ): Promise<Operator> {
    return this._client.post<Operator>({
      path: `/v0.1/me/accounts`,
      body,
      ...options,
    });
  }

  createSubAccountWithResponse(
    body: CreateSubAccountParams,
    options?: RequestOptions,
  ): Promise<WithResponse<Operator>> {
    return this._client.postWithResponse<Operator>({
      path: `/v0.1/me/accounts`,
      body,
      ...options,
    });
  }

  /**
   * Returns specific operator.
   */
  compatGetOperator(
    operatorId: number,
    options?: RequestOptions,
  ): Promise<Operator> {
    return this._client.get<Operator>({
      path: `/v0.1/me/accounts/${operatorId}`,
      ...options,
    });
  }

  compatGetOperatorWithResponse(
    operatorId: number,
    options?: RequestOptions,
  ): Promise<WithResponse<Operator>> {
    return this._client.getWithResponse<Operator>({
      path: `/v0.1/me/accounts/${operatorId}`,
      ...options,
    });
  }

  /**
   * Updates operator. If the operator was disabled and their password is updated they will be unblocked.
   */
  updateSubAccount(
    operatorId: number,
    body: UpdateSubAccountParams,
    options?: RequestOptions,
  ): Promise<Operator> {
    return this._client.put<Operator>({
      path: `/v0.1/me/accounts/${operatorId}`,
      body,
      ...options,
    });
  }

  updateSubAccountWithResponse(
    operatorId: number,
    body: UpdateSubAccountParams,
    options?: RequestOptions,
  ): Promise<WithResponse<Operator>> {
    return this._client.putWithResponse<Operator>({
      path: `/v0.1/me/accounts/${operatorId}`,
      body,
      ...options,
    });
  }
}
