// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.
import type { HTTPClient } from "./client";
import { EventBase, type EventPayload, UnknownEvent } from "./event";
import type { Member } from "./types/member";
import type { Reader } from "./types/reader";
import type { Role } from "./types/role";
/** A members.created notification. Call fetchObject() to retrieve the latest Member. */
export class MemberCreatedEvent extends EventBase<Member> {
  declare readonly type: "members.created";
}
/** A members.deleted notification. Call fetchObject() to retrieve the latest Member. */
export class MemberDeletedEvent extends EventBase<Member> {
  declare readonly type: "members.deleted";
}
/** A members.updated notification. Call fetchObject() to retrieve the latest Member. */
export class MemberUpdatedEvent extends EventBase<Member> {
  declare readonly type: "members.updated";
}
/** A readers.created notification. Call fetchObject() to retrieve the latest Reader. */
export class ReaderCreatedEvent extends EventBase<Reader> {
  declare readonly type: "readers.created";
}
/** A readers.deleted notification. Call fetchObject() to retrieve the latest Reader. */
export class ReaderDeletedEvent extends EventBase<Reader> {
  declare readonly type: "readers.deleted";
}
/** A roles.created notification. Call fetchObject() to retrieve the latest Role. */
export class RoleCreatedEvent extends EventBase<Role> {
  declare readonly type: "roles.created";
}
/** A roles.deleted notification. Call fetchObject() to retrieve the latest Role. */
export class RoleDeletedEvent extends EventBase<Role> {
  declare readonly type: "roles.deleted";
}
/** A roles.updated notification. Call fetchObject() to retrieve the latest Role. */
export class RoleUpdatedEvent extends EventBase<Role> {
  declare readonly type: "roles.updated";
}
/** Known wire event names and their notification classes. */
export interface EventMap {
  "members.created": MemberCreatedEvent;
  "members.deleted": MemberDeletedEvent;
  "members.updated": MemberUpdatedEvent;
  "readers.created": ReaderCreatedEvent;
  "readers.deleted": ReaderDeletedEvent;
  "roles.created": RoleCreatedEvent;
  "roles.deleted": RoleDeletedEvent;
  "roles.updated": RoleUpdatedEvent;
}
/** A recognized event notification or {@link UnknownEvent}. Narrow with instanceof to access a specific resource type. */
export type EventNotification = EventMap[keyof EventMap] | UnknownEvent;
/** @internal Construct the typed notification from the decoded JSON object. */
export function createEvent(
  payload: EventPayload,
  client: HTTPClient,
): EventNotification {
  switch (payload.type) {
    case "members.created":
      return new MemberCreatedEvent(payload, client);
    case "members.deleted":
      return new MemberDeletedEvent(payload, client);
    case "members.updated":
      return new MemberUpdatedEvent(payload, client);
    case "readers.created":
      return new ReaderCreatedEvent(payload, client);
    case "readers.deleted":
      return new ReaderDeletedEvent(payload, client);
    case "roles.created":
      return new RoleCreatedEvent(payload, client);
    case "roles.deleted":
      return new RoleDeletedEvent(payload, client);
    case "roles.updated":
      return new RoleUpdatedEvent(payload, client);
    default:
      return new UnknownEvent(payload, client);
  }
}
