// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import { HTTPClient } from "./client";

export type { APIConfig } from "./client";
export type { RequestOptions, WithResponse } from "./core";
export { APIError, SumUpError } from "./core";

import type { EventNotification } from "./events";
import type { EventBody, EventCallback } from "./events-handler";
import {
  EventsHandler,
  parseEventNotification,
  parseEventNotificationWithoutVerification,
} from "./events-handler";

export type { EventObject } from "./event";
export { UnknownEvent } from "./event";
export type { EventNotification } from "./events";
export {
  MemberCreatedEvent,
  MemberDeletedEvent,
  MemberUpdatedEvent,
  ReaderCreatedEvent,
  ReaderDeletedEvent,
} from "./events";
export type { EventBody, EventCallback } from "./events-handler";
export {
  EventCallbackError,
  EventError,
  EventPayloadError,
  EventSignatureError,
  EventSignatureExpiredError,
  EventsHandler,
  EventTimestampError,
  SIGNATURE_HEADER,
  verifyEventSignature,
} from "./events-handler";
export * from "./resources/checkouts";
export * from "./types";

import { Checkouts } from "./resources/checkouts";

export * from "./resources/customers";

import { Customers } from "./resources/customers";

export * from "./resources/members";

import { Members } from "./resources/members";

export * from "./resources/memberships";

import { Memberships } from "./resources/memberships";

export * from "./resources/merchants";

import { Merchants } from "./resources/merchants";

export * from "./resources/payouts";

import { Payouts } from "./resources/payouts";

export * from "./resources/readers";

import { Readers } from "./resources/readers";

export * from "./resources/receipts";

import { Receipts } from "./resources/receipts";

export * from "./resources/roles";

import { Roles } from "./resources/roles";

export * from "./resources/transactions";

import { Transactions } from "./resources/transactions";

export class SumUp extends HTTPClient {
  /**
   * Create an event handler bound to this API client.
   * Register typed callbacks with on(); events without a callback reach fallback.
   *
   * @param secret - Your event signing secret, not an API key.
   * @param fallback - Required callback for unregistered or unrecognized event types.
   */
  eventsHandler(secret: string, fallback: EventCallback): EventsHandler {
    return new EventsHandler(this, secret, fallback);
  }
  /**
   * Verify an incoming event's signature and timestamp, then parse it without running callbacks.
   * For already verified, trusted payloads, use {@link SumUp.parseEventNotificationWithoutVerification}.
   *
   * @param secret - Your event signing secret, not an API key.
   * @param body - Unchanged request body, read before JSON parsing.
   * @param signature - Complete value of the {@link SIGNATURE_HEADER} header.
   * @returns A typed notification, or {@link UnknownEvent} for an unrecognized type.
   * @throws {@link EventSignatureError} If verification fails, including the five-minute timestamp check.
   * @throws {@link EventPayloadError} If the body cannot be decoded as a JSON object.
   */
  parseEventNotification(
    secret: string,
    body: EventBody,
    signature: string,
  ): Promise<EventNotification> {
    return parseEventNotification(this, secret, body, signature);
  }
  /**
   * Parse an event without checking its signature or signing timestamp.
   * Use only for fixtures or trusted payloads verified before being queued.
   * Use {@link SumUp.parseEventNotification} for incoming HTTP deliveries.
   *
   * @param body - The stored event payload.
   * @returns A typed notification, or {@link UnknownEvent} for an unrecognized type.
   * @throws {@link EventPayloadError} If the body cannot be decoded as a JSON object.
   */
  parseEventNotificationWithoutVerification(
    body: EventBody,
  ): EventNotification {
    return parseEventNotificationWithoutVerification(this, body);
  }

  /** Access the Checkouts API endpoints. */
  checkouts: Checkouts = new Checkouts(this);
  /** Access the Customers API endpoints. */
  customers: Customers = new Customers(this);
  /** Access the Members API endpoints. */
  members: Members = new Members(this);
  /** Access the Memberships API endpoints. */
  memberships: Memberships = new Memberships(this);
  /** Access the Merchants API endpoints. */
  merchants: Merchants = new Merchants(this);
  /** Access the Payouts API endpoints. */
  payouts: Payouts = new Payouts(this);
  /** Access the Readers API endpoints. */
  readers: Readers = new Readers(this);
  /** Access the Receipts API endpoints. */
  receipts: Receipts = new Receipts(this);
  /** Access the Roles API endpoints. */
  roles: Roles = new Roles(this);
  /** Access the Transactions API endpoints. */
  transactions: Transactions = new Transactions(this);
}

export default SumUp;
