// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import {
  type APIPromise,
  APIResource,
  isRequestOptions,
  type RequestOptions,
} from "../../core";
import type {
  ListPersonsResponseBody,
  Merchant,
  Person,
  Problem,
} from "../../types";
export type GetMerchantQueryParams = {
  version?: string;
};

export type ListPersonsQueryParams = {
  version?: string;
};

export type GetPersonQueryParams = {
  version?: string;
};

export class Merchants extends APIResource {
  /**
   * Retrieve a merchant.
   */
  get(
    merchantCode: string,
    query?: GetMerchantQueryParams,
    options?: RequestOptions,
  ): APIPromise<Merchant, Problem>;
  get(
    merchantCode: string,
    options?: RequestOptions,
  ): APIPromise<Merchant, Problem>;
  get(
    merchantCode: string,
    queryOrOptions?: GetMerchantQueryParams | RequestOptions,
    options?: RequestOptions,
  ): APIPromise<Merchant, Problem> {
    const query = isRequestOptions(queryOrOptions) ? undefined : queryOrOptions;
    const requestOptions = isRequestOptions(queryOrOptions)
      ? queryOrOptions
      : options;
    return this._client.get<Merchant, Problem>({
      path: `/v1/merchants/${merchantCode}`,
      query,
      ...requestOptions,
    });
  }

  /**
   * Returns a list of persons related to the merchant.
   */
  listPersons(
    merchantCode: string,
    query?: ListPersonsQueryParams,
    options?: RequestOptions,
  ): APIPromise<ListPersonsResponseBody, Problem>;
  listPersons(
    merchantCode: string,
    options?: RequestOptions,
  ): APIPromise<ListPersonsResponseBody, Problem>;
  listPersons(
    merchantCode: string,
    queryOrOptions?: ListPersonsQueryParams | RequestOptions,
    options?: RequestOptions,
  ): APIPromise<ListPersonsResponseBody, Problem> {
    const query = isRequestOptions(queryOrOptions) ? undefined : queryOrOptions;
    const requestOptions = isRequestOptions(queryOrOptions)
      ? queryOrOptions
      : options;
    return this._client.get<ListPersonsResponseBody, Problem>({
      path: `/v1/merchants/${merchantCode}/persons`,
      query,
      ...requestOptions,
    });
  }

  /**
   * Returns a single person related to the merchant.
   */
  getPerson(
    merchantCode: string,
    personId: string,
    query?: GetPersonQueryParams,
    options?: RequestOptions,
  ): APIPromise<Person, Problem>;
  getPerson(
    merchantCode: string,
    personId: string,
    options?: RequestOptions,
  ): APIPromise<Person, Problem>;
  getPerson(
    merchantCode: string,
    personId: string,
    queryOrOptions?: GetPersonQueryParams | RequestOptions,
    options?: RequestOptions,
  ): APIPromise<Person, Problem> {
    const query = isRequestOptions(queryOrOptions) ? undefined : queryOrOptions;
    const requestOptions = isRequestOptions(queryOrOptions)
      ? queryOrOptions
      : options;
    return this._client.get<Person, Problem>({
      path: `/v1/merchants/${merchantCode}/persons/${personId}`,
      query,
      ...requestOptions,
    });
  }
}
