// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import {
  APIResource,
  type RequestOptions,
  type WithResponse,
} from "../../core";
import type { ListPersonsResponseBody, Merchant, Person } from "../../types";
/**
 * API resource for the Merchants endpoints.
 *
 * A Merchant represents a single business which can use SumUp products like payment processing.
 */
export class Merchants extends APIResource {
  /**
   * Returns a Merchant for a valid Merchant code.
   */
  get(merchantCode: string, options?: RequestOptions): Promise<Merchant> {
    return this._client.get<Merchant>({
      path: `/v1/merchants/${merchantCode}`,
      ...options,
    });
  }

  getWithResponse(
    merchantCode: string,
    options?: RequestOptions,
  ): Promise<WithResponse<Merchant>> {
    return this._client.getWithResponse<Merchant>({
      path: `/v1/merchants/${merchantCode}`,
      ...options,
    });
  }

  /**
   * Returns the Persons related to a Merchant.
   */
  listPersons(
    merchantCode: string,
    options?: RequestOptions,
  ): Promise<ListPersonsResponseBody> {
    return this._client.get<ListPersonsResponseBody>({
      path: `/v1/merchants/${merchantCode}/persons`,
      ...options,
    });
  }

  listPersonsWithResponse(
    merchantCode: string,
    options?: RequestOptions,
  ): Promise<WithResponse<ListPersonsResponseBody>> {
    return this._client.getWithResponse<ListPersonsResponseBody>({
      path: `/v1/merchants/${merchantCode}/persons`,
      ...options,
    });
  }

  /**
   * Returns a single Person related to a Merchant.
   */
  getPerson(
    merchantCode: string,
    personId: string,
    options?: RequestOptions,
  ): Promise<Person> {
    return this._client.get<Person>({
      path: `/v1/merchants/${merchantCode}/persons/${personId}`,
      ...options,
    });
  }

  getPersonWithResponse(
    merchantCode: string,
    personId: string,
    options?: RequestOptions,
  ): Promise<WithResponse<Person>> {
    return this._client.getWithResponse<Person>({
      path: `/v1/merchants/${merchantCode}/persons/${personId}`,
      ...options,
    });
  }
}
