// Code generated by @sumup/ts-sdk-gen@0.0.1. DO NOT EDIT.

import * as Core from "../../core";

/**
 * Profile information.
 */
export type Account = {
  /**
   * The role of the user.
   */
  type?: "normal" | "operator";
  /**
   * Username of the user profile.
   */
  username?: string;
};

/**
 * Country Details
 */
export type CountryDetails = {
  /**
   * Currency ISO 4217 code
   */
  currency?: string;
  /**
   * Country EN name
   */
  en_name?: string;
  /**
   * Country ISO code
   */
  iso_code?: string;
  /**
   * Country native name
   */
  native_name?: string;
};

/**
 * TimeOffset Details
 */
export type TimeoffsetDetails = {
  /**
   * Daylight Saving Time
   */
  dst?: boolean;
  /**
   * UTC offset
   */
  offset?: number;
  /**
   * Postal code
   */
  post_code?: string;
};

/**
 * Details of the registered address.
 */
export type AddressWithDetails = {
  /**
   * Address line 1
   */
  address_line1?: string;
  /**
   * Address line 2
   */
  address_line2?: string;
  /**
   * City
   */
  city?: string;
  /**
   * undefined
   */
  company?: string;
  /**
   * Country ISO 3166-1 code
   */
  country?: string;
  country_details?: CountryDetails;
  /**
   * undefined
   */
  first_name?: string;
  /**
   * Landline number
   */
  landline?: string;
  /**
   * undefined
   */
  last_name?: string;
  /**
   * Postal code
   */
  post_code?: string;
  /**
   * Region code
   */
  region_code?: string;
  /**
   * Country region id
   */
  region_id?: number;
  /**
   * Region name
   */
  region_name?: string;
  /**
   * undefined
   */
  state_id?: string;
  timeoffset_details?: TimeoffsetDetails;
};

/**
 * Mobile app settings
 */
export type AppSettings = {
  /**
   * Advanced mode.
   */
  advanced_mode?: string;
  /**
   * Barcode scanner.
   */
  barcode_scanner?: string;
  /**
   * Cash payment.
   */
  cash_payment?: string;
  /**
   * Checkout preference
   */
  checkout_preference?: string;
  /**
   * Expected max transaction amount.
   */
  expected_max_transaction_amount?: number;
  /**
   * Include vat.
   */
  include_vat?: boolean;
  /**
   * Manual entry.
   */
  manual_entry?: string;
  /**
   * Manual entry tutorial.
   */
  manual_entry_tutorial?: boolean;
  /**
   * Mobile payment.
   */
  mobile_payment?: string;
  /**
   * Mobile payment tutorial.
   */
  mobile_payment_tutorial?: boolean;
  /**
   * Reader payment.
   */
  reader_payment?: string;
  /**
   * Referral.
   */
  referral?: string;
  /**
   * Tax enabled.
   */
  tax_enabled?: boolean;
  /**
   * Terminal mode tutorial.
   */
  terminal_mode_tutorial?: boolean;
  /**
   * Tip rates.
   */
  tip_rates?: number[];
  /**
   * Tipping.
   */
  tipping?: string;
};

export type BankAccount = {
  /**
   * Account category - business or personal
   */
  account_category?: string;
  account_holder_name?: string;
  /**
   * Account number
   */
  account_number?: string;
  /**
   * Type of the account
   */
  account_type?: string;
  /**
   * Bank code
   */
  bank_code?: string;
  /**
   * Bank name
   */
  bank_name?: string;
  /**
   * Branch code
   */
  branch_code?: string;
  /**
   * Creation date of the bank account
   */
  created_at?: string;
  /**
   * IBAN
   */
  iban?: string;
  /**
   * The primary bank account is the one used for payouts
   */
  primary?: boolean;
  /**
   * Status in the verification process
   */
  status?: string;
  /**
   * SWIFT code
   */
  swift?: string;
};

/**
 * Business owners information.
 */
export type BusinessOwners = {
  /**
   * Date of birth
   */
  date_of_birth?: string;
  /**
   * BO's first name
   */
  first_name?: string;
  /**
   * BO's Landline
   */
  landline?: string;
  /**
   * BO's last name of the user
   */
  last_name?: string;
  /**
   * Mobile phone number
   */
  mobile_phone?: string;
  /**
   * Ownership percentage
   */
  ownership?: number;
}[];

/**
 * Doing Business As information
 */
export type DoingBusinessAs = {
  address?: {
    /**
     * Address line 1
     */
    address_line1?: string;
    /**
     * Address line 2
     */
    address_line2?: string;
    /**
     * City
     */
    city?: string;
    /**
     * Country ISO 3166-1 code
     */
    country?: string;
    /**
     * Postal code
     */
    post_code?: string;
    /**
     * Country region ID
     */
    region_id?: number;
    /**
     * Country region name
     */
    region_name?: string;
  };
  /**
   * Doing business as name
   */
  business_name?: string;
  /**
   * Doing business as company registration number
   */
  company_registration_number?: string;
  /**
   * Doing business as email
   */
  email?: string;
  /**
   * Doing business as VAT ID
   */
  vat_id?: string;
  /**
   * Doing business as website
   */
  website?: string;
};

/**
 * Error message for forbidden requests.
 */
export type ErrorForbidden = {
  /**
   * Platform code for the error.
   */
  error_code?: string;
  /**
   * Short description of the error.
   */
  error_message?: string;
  /**
   * HTTP status code for the error.
   */
  status_code?: string;
};

/**
 * Id of the legal type of the merchant profile
 */
export type LegalType = {
  /**
   * Legal type short description
   */
  description?: string;
  /**
   * Legal type description
   */
  full_description?: string;
  /**
   * Unique id
   */
  id?: number;
  /**
   * Sole trader legal type if true
   */
  sole_trader?: boolean;
};

/**
 * Merchant settings &#40;like \"payout_type\", \"payout_period\"&#41;
 */
export type MerchantSettings = {
  /**
   * Whether merchant will receive daily payout emails
   */
  daily_payout_email?: boolean;
  /**
   * Whether merchant has gross settlement enabled
   */
  gross_settlement?: boolean;
  /**
   * Whether merchant will receive monthly payout emails
   */
  monthly_payout_email?: boolean;
  /**
   * Whether merchant can make MOTO payments
   */
  moto_payment?: "UNAVAILABLE" | "ENFORCED" | "ON" | "OFF";
  /**
   * Payout Instrument
   */
  payout_instrument?: string;
  /**
   * Whether merchant will receive payouts on demand
   */
  payout_on_demand?: boolean;
  /**
   * Whether merchant can edit payouts on demand
   */
  payout_on_demand_available?: boolean;
  /**
   * Payout frequency
   */
  payout_period?: string;
  /**
   * Payout type
   */
  payout_type?: string;
  /**
   * Whether to show printers in mobile app
   */
  printers_enabled?: boolean;
  /**
   * Stone merchant code
   */
  stone_merchant_code?: string;
  /**
   * Whether to show tax in receipts &#40;saved per transaction&#41;
   */
  tax_enabled?: boolean;
};

/**
 * Merchant VAT rates
 */
export type VatRates = {
  /**
   * Country ISO code
   */
  country?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Internal ID
   */
  id?: number;
  /**
   * Ordering
   */
  ordering?: number;
  /**
   * Rate
   */
  rate?: number;
};

/**
 * Account's merchant profile
 */
export type MerchantProfile = {
  address?: AddressWithDetails;
  bank_accounts?: BankAccount[];
  business_owners?: BusinessOwners;
  /**
   * Company name
   */
  company_name?: string;
  /**
   * Company registration number
   */
  company_registration_number?: string;
  /**
   * Merchant country code formatted according to [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) &#40;for internal usage only&#41;
   */
  country?: string;
  doing_business_as?: DoingBusinessAs;
  /**
   * True if the merchant is extdev
   */
  extdev?: boolean;
  legal_type?: LegalType;
  /**
   * Merchant locale &#40;for internal usage only&#41;
   */
  locale?: string;
  /**
   * Merchant category code
   */
  merchant_category_code?: string;
  /**
   * Unique identifying code of the merchant profile
   */
  merchant_code?: string;
  /**
   * Mobile phone number
   */
  mobile_phone?: string;
  /**
   * Nature and purpose of the business
   */
  nature_and_purpose?: string;
  /**
   * True if the payout zone of this merchant is migrated
   */
  payout_zone_migrated?: boolean;
  /**
   * Permanent certificate access code &#40;Portugal&#41;
   */
  permanent_certificate_access_code?: string;
  settings?: MerchantSettings;
  /**
   * Vat ID
   */
  vat_id?: string;
  vat_rates?: VatRates;
  /**
   * Website
   */
  website?: string;
};

/**
 * User permissions
 */
export type Permissions = {
  /**
   * Create MOTO payments
   */
  create_moto_payments?: boolean;
  /**
   * Create referral
   */
  create_referral?: boolean;
  /**
   * Can view full merchant transaction history
   */
  full_transaction_history_view?: boolean;
  /**
   * Refund transactions
   */
  refund_transactions?: boolean;
};

/**
 * Account's personal profile.
 */
export type PersonalProfile = {
  address?: AddressWithDetails;
  complete?: boolean;
  /**
   * Date of birth
   */
  date_of_birth?: string;
  /**
   * First name of the user
   */
  first_name?: string;
  /**
   * Last name of the user
   */
  last_name?: string;
  /**
   * Mobile phone number
   */
  mobile_phone?: string;
};

/**
 * Merchant Account
 *
 * Details of the merchant account.
 */
export type MerchantAccount = {
  account?: Account;
  app_settings?: AppSettings;
  /**
   * Merchant comes from payleven BR migration
   */
  is_migrated_payleven_br?: boolean;
  merchant_profile?: MerchantProfile;
  permissions?: Permissions;
  personal_profile?: PersonalProfile;
};

export type GetAccountQueryParams = {
  "include[]"?: (
    | "settings"
    | "doing_business_as"
    | "bank_accounts"
    | "app_settings"
    | "country_details"
  )[];
};

export type ListBankAccountsQueryParams = {
  primary?: boolean;
};

export type ListBankAccountsResponse = BankAccount[];

export type ListBankAccountsV11QueryParams = {
  primary?: boolean;
};

export type ListBankAccountsV11Response = BankAccount[];

export class Merchant extends Core.APIResource {
  /**
   * Retrieve a profile
   */
  get(
    query?: GetAccountQueryParams,
    params?: Core.FetchParams,
  ): Core.APIPromise<MerchantAccount> {
    return this._client.get<MerchantAccount>({
      path: `/v0.1/me`,
      query,
      ...params,
    });
  }

  /**
   * Retrieve a merchant profile
   */
  getMerchantProfile(
    params?: Core.FetchParams,
  ): Core.APIPromise<MerchantProfile> {
    return this._client.get<MerchantProfile>({
      path: `/v0.1/me/merchant-profile`,
      ...params,
    });
  }

  /**
   * List bank accounts
   */
  listBankAccountsDeprecated(
    query?: ListBankAccountsQueryParams,
    params?: Core.FetchParams,
  ): Core.APIPromise<BankAccount[]> {
    return this._client.get<BankAccount[]>({
      path: `/v0.1/me/merchant-profile/bank-accounts`,
      query,
      ...params,
    });
  }

  /**
   * Retrieve DBA
   */
  getDoingBusinessAs(
    params?: Core.FetchParams,
  ): Core.APIPromise<DoingBusinessAs> {
    return this._client.get<DoingBusinessAs>({
      path: `/v0.1/me/merchant-profile/doing-business-as`,
      ...params,
    });
  }

  /**
   * Get settings
   */
  getSettings(params?: Core.FetchParams): Core.APIPromise<MerchantSettings> {
    return this._client.get<MerchantSettings>({
      path: `/v0.1/me/merchant-profile/settings`,
      ...params,
    });
  }

  /**
   * Retrieve a personal profile
   */
  getPersonalProfile(
    params?: Core.FetchParams,
  ): Core.APIPromise<PersonalProfile> {
    return this._client.get<PersonalProfile>({
      path: `/v0.1/me/personal-profile`,
      ...params,
    });
  }

  /**
   * List bank accounts
   */
  listBankAccounts(
    merchantCode: string,
    query?: ListBankAccountsV11QueryParams,
    params?: Core.FetchParams,
  ): Core.APIPromise<BankAccount[]> {
    return this._client.get<BankAccount[]>({
      path: `/v1.1/merchants/${merchantCode}/bank-accounts`,
      query,
      ...params,
    });
  }
}

export declare namespace Merchant {
  export type {
    Account,
    AddressWithDetails,
    AppSettings,
    BankAccount,
    BusinessOwners,
    CountryDetails,
    DoingBusinessAs,
    ErrorForbidden,
    GetAccountQueryParams,
    LegalType,
    ListBankAccountsQueryParams,
    ListBankAccountsV11QueryParams,
    MerchantAccount,
    MerchantProfile,
    MerchantSettings,
    Permissions,
    PersonalProfile,
    TimeoffsetDetails,
    VatRates,
  };
}
