name: Release

on:
  release:
    types:
      - published

defaults:
  run:
    working-directory: ./sdk

permissions:
  id-token: write # Needed for provenance
  packages: write # Needed to publish package to GitHub package registry
  contents: read # Needed for publishing to JSR

jobs:
  publish:
    name: Publish
    if: '!github.event.prerelease'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ./sdk/package.json
          cache: npm
          cache-dependency-path: ./sdk/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --provenance --access public

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ./sdk/package.json
          cache: npm
          cache-dependency-path: ./sdk/package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sumup'

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npm publish --provenance --access public

      - name: Publish to JSR
        run: npx jsr publish
