// Code generated by @sumup/sumup-ts-codegen. DO NOT EDIT.

import { type APIPromise, APIResource, type RequestOptions } from "../../core";
import type { Metadata, Problem, Role } from "../../types";
export type ListMerchantRolesResponse = { items: Role[] };

export type CreateMerchantRoleParams = {
  /**
   * User-defined name of the role.
   */
  name: string;
  /**
   * User's permissions.
   */
  permissions: string[];
  metadata?: Metadata;
  /**
   * User-defined description of the role.
   */
  description?: string;
};

export type UpdateMerchantRoleParams = {
  /**
   * User-defined name of the role.
   */
  name?: string;
  /**
   * User's permissions.
   */
  permissions?: string[];
  /**
   * User-defined description of the role.
   */
  description?: string;
};

export class Roles extends APIResource {
  /**
   * List merchant's custom roles.
   */
  list(
    merchantCode: string,
    options?: RequestOptions,
  ): APIPromise<ListMerchantRolesResponse, Problem> {
    return this._client.get<ListMerchantRolesResponse, Problem>({
      path: `/v0.1/merchants/${merchantCode}/roles`,
      ...options,
    });
  }

  /**
   * Create a custom role for the merchant. Roles are defined by the set of permissions that they grant to the members that they are assigned to.
   */
  create(
    merchantCode: string,
    body: CreateMerchantRoleParams,
    options?: RequestOptions,
  ): APIPromise<Role, Problem> {
    return this._client.post<Role, Problem>({
      path: `/v0.1/merchants/${merchantCode}/roles`,
      body,
      ...options,
    });
  }

  /**
   * Retrieve a custom role by ID.
   */
  get(
    merchantCode: string,
    roleId: string,
    options?: RequestOptions,
  ): APIPromise<Role, Problem> {
    return this._client.get<Role, Problem>({
      path: `/v0.1/merchants/${merchantCode}/roles/${roleId}`,
      ...options,
    });
  }

  /**
   * Delete a custom role.
   */
  delete(
    merchantCode: string,
    roleId: string,
    options?: RequestOptions,
  ): APIPromise<void, Problem> {
    return this._client.delete<void, Problem>({
      path: `/v0.1/merchants/${merchantCode}/roles/${roleId}`,
      ...options,
    });
  }

  /**
   * Update a custom role.
   */
  update(
    merchantCode: string,
    roleId: string,
    body: UpdateMerchantRoleParams,
    options?: RequestOptions,
  ): APIPromise<Role, Problem> {
    return this._client.patch<Role, Problem>({
      path: `/v0.1/merchants/${merchantCode}/roles/${roleId}`,
      body,
      ...options,
    });
  }
}
